### ISSUE TITLE
Investigate backfilling SSURGO data with STATSGO

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1014]
Can [STATSGO2](http://www.nrcs.usda.gov/wps/portal/nrcs/detail/soils/survey/geo/?cid=nrcs142p2_053629) be used to fill in the mostly urban gaps in soil coverage for SSURGO?

**Comment by chitchens** [comment]
This is vector data, and can't be dropped in as-is since we're using raster data. The dataset that we're currently using is the gSSURGO, where the "g" is for gridded (i.e., raster), and I can't find a gSTATSGO variant of STATSGO. 

It's possible that it could be rasterized and used to backfill the gSSURGO data, although that's not a trivial undertaking.
