### ISSUE TITLE
Snapshot incorrect after panning

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1099]
A bug was reported in which the ITSI snapshot fails to render or displays the incorrect location after the first snapshot is taken. 

Map #1:
![screen shot 2016-01-18 at 12 57 58 pm](https://cloud.githubusercontent.com/assets/12868342/12398676/261aa5aa-bde3-11e5-9f8c-d450bf222d7e.png)

Snapshot:
![screen shot 2016-01-18 at 12 47 42 pm](https://cloud.githubusercontent.com/assets/12868342/12398720/6652f7f8-bde3-11e5-9b6b-9aeb4fa0b942.png)

Map #2 (after panning)
![screen shot 2016-01-18 at 12 48 45 pm](https://cloud.githubusercontent.com/assets/12868342/12398698/474e6784-bde3-11e5-9726-4429b9b2d900.png)

Snapshot #2:
![screen shot 2016-01-18 at 12 49 51 pm](https://cloud.githubusercontent.com/assets/12868342/12398708/574347fe-bde3-11e5-8000-4f43f2f640aa.png)

Snapshot #3 (after zooming out)
![screen shot 2016-01-18 at 12 50 14 pm](https://cloud.githubusercontent.com/assets/12868342/12398726/736abb06-bde3-11e5-9eb0-0cb4a87cca72.png)

**To replicate:**
1. Log into the ITSI portal via MMW or learn.staging.concord.org and run the MMW Staging activity.
2. Log out and then select continue as ITSI to log back in
3. Take a snapshot
4. Pan to a different location and take another snapshot; you should see a screenshot of the first location, not the new one.
5. Zoom and take a snapshot; it should be missing tiles (I could reproduce this error less reliably than the panning issue).

*Note:* The only way to reliably reproduce this is to start from a completely new project by logging in again. A hard refresh will fix the problem, as will returning to the "Classes and Offerings" page and running the activity again.

**Comment by rajadain** [comment]
Is there value in letting people log out if they are in embed mode? If we remove the option to log out, then we can avoid this use case entirely.

**Comment by ajrobbins** [comment]
The log out/ login behavior that was necessary for me to replicate this issue may have been related to me using our general tstudent2 login for learn.staging; it has some saved scenarios and I was only able to replicate this issue by logging out and logging in fresh. So it's possible that it's not related to the logging back in at all.

**Comment by rajadain** [comment]
Alright, I'll see if I can test this with a completely blank slate.

**Comment by rajadain** [comment]
Okay, this seems to be an edge case not covered by #978. The essence of the problem is that Leaflet uses CSS 3D transforms to manipulate the map efficiently, but these are not supported by PhantomJS which is used by ITSI to take screenshots. So, in cases when we know we are in an `itsi_embed` mode, [we turn 3D transforms off](https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/apps/core/templates/base.html#L63-L68):

```javascript
window.L_DISABLE_3D = true;
```

But how do we know we are in embed mode? For that we use the URL flag `?itsi_embed=true` as the signifier, which when encountered [sets a session variable](https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/apps/user/middleware.py#L33). This session variable is [used to populate `client_settings`](https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/apps/home/views.py#L121) on the server side, which in turn [populates `clientSettings` on the client side](https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/apps/core/templates/base.html#L61-L68), and is used to determine if `window.L_DISABLE_3D` should be turned on or off.

This works correctly in _most_ cases, since it relies on the `?itsi_embed=true` flag in the URL that is configured into the URL in the ITSI portal. That flag is only present once, and is removed as soon as it is processed. This is fine, since once it is encountered we record it in the session which survives page refreshes, thus it doesn't need to be there in every page load. However, as soon as the user logs out, the session is destroyed. If they log back in using the ITSI button, they now have a new session, one not started with the `?itsi_embed=true` flag, one in which `window.L_DISABLE_3D` does not exist, one which cannot be rendered by PhantomJS.

Thus, removing the log out option for embed mode seems to be the best move going forward. I think it makes sense in the embed mode use case as well, which automatically logs you in, and even creates an account for you if you don't have one.

This final use case, when you are initially logged out and ITSI creates an account for you, is one where the flag fails, and I am looking in to it now. So the solution should consist of two things: fix setting the flag if creating a new user, and not allowing users to log out in embed mode.
