### ISSUE TITLE
Exception: Point located outside the watershed.

### ISSUE THREAD

**Issue by hectcastro** [WikiWatershed/model-my-watershed#1160]
View details in Rollbar: [https://rollbar.com/Azavea/MMW/items/35/](https://rollbar.com/Azavea/MMW/items/35/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "apps/modeling/tasks.py", line 42, in start_rwd_job
    raise Exception(response_json['error'])
Exception: Point located outside the watershed.
```

**Comment by mmcfarland** [comment]
This is going to occur when an RWD request is made in an area oustide of coverage, and is currently handled in the UI in a too subtle way:

![screenshot from 2016-02-19 16 17 37](https://cloud.githubusercontent.com/assets/1014341/13189276/665db378-d724-11e5-8778-856d35a94f63.png)

Since this is a known limitation of the RWD project, we should probably handle this in a way that doesn't require raising, even though the error case is expected.

Ideally, this is handled as input validation by doing a point in polygon check that the coordinates are inside the DRB boundary, and not allowing the request to make it all the way to the RWD service in that case.
