### ISSUE TITLE
Error popup when you cancel "Delineate Watershed" drawing

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#1181]
If you press Esc to cancel placing a stream network watershed delineation marker, you'll get an error popup "Unable to delineate watershed at this location".

Caused by #1175.

**Comment by kellyi** [comment]
Will work on this one since it's adjacent to something I was working on in #1160

**Comment by kdeloach** [comment]
After adding the RWD alert message, I realized that we don't have a way to distinguish a failure from a cancellation for drawing actions. 

Normal draw actions (square mile and free draw) can't really "fail", but they can be cancelled with Esc. Delineating a point will fail to return a polygon if RWD throws an error.

I might be able to help with this if you need ideas.

**Comment by kellyi** [comment]
Sounds good. 

I was thinking of maybe having the RWD alert only show if the failed action has sent it a message to display; otherwise it'd just "fail" silently -- which is how you'd want it to fail on Esc or clicking Reset. 

Upside's that the failure messages could be a little more specific to each action; downside's that they'd need to be added for all failed actions that should show a message.
