### ISSUE TITLE
Basemaps appear to be misaligned

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1237]
The "satellite with roads" and "terrain" basemaps appear to be shifted slightly south from the "satellite" and "streets" basemaps. This is a bit difficult to observe, but is helped by turning the NLCD overlay on. You can see that the roads on the streets and satellite basemaps align with the NLCD land use classification, but the other two basemaps do not.

It's unclear if this issue is actually zoom-dependent, but it's pretty much only perceptible around zoom levels 14-15.

Streets (zoom level 15)
![screen shot 2016-04-11 at 1 17 54 pm](https://cloud.githubusercontent.com/assets/12868342/14436079/01980b4e-ffe9-11e5-80d9-911fca74e070.png)

Terrain (zoom level 15)
![screen shot 2016-04-11 at 1 17 59 pm](https://cloud.githubusercontent.com/assets/12868342/14436085/07bbc3c6-ffe9-11e5-91e1-4c7bee3db869.png)

**Comment by mmcfarland** [comment]
This actually appears to not be zoom dependent or projection related.  When zoomed out and displaying a DEP municipal boundary, you can see the offset around the DE/PA border.  The offset is not spatially consistent when zooming in, but does appear to be pixel/viewport consistent with a gutter observed at the top of the map when these google layers are turned out:

![screenshot from 2016-07-19 11 17 20](https://cloud.githubusercontent.com/assets/1014341/16955470/bdd5bc82-4da2-11e6-8582-dcfc11e9818e.png)

I believe this is the same root cause of #1238 as well.  

The culprit seems to be this [css rule](https://github.com/WikiWatershed/model-my-watershed/blob/f13c3c444c902daf4ae591d3e3a2fad59980a3e5/src/mmw/sass/base/_map.scss#L105-L107) which is adding the gutter.  Disabling that rule results in the correct display:

![screenshot from 2016-07-19 11 24 42](https://cloud.githubusercontent.com/assets/1014341/16955640/6765e4c0-4da3-11e6-9880-b5bb12032c13.png)

Apparently the class `leaflet-top` only gets added to the map container for Google base maps, it does not appear to be used when other layer sources are used.

**Comment by caseypt** [comment]
It looks like the Google leaflet plugin adds this class https://github.com/shramov/leaflet-plugins/blob/master/layer/tile/Google.js#L91.

I'll try and make our rule more specific.
