### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by hectcastro** [WikiWatershed/model-my-watershed#1386]
View details in Rollbar: [https://rollbar.com/Azavea/MMW/items/97/](https://rollbar.com/Azavea/MMW/items/97/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "apps/modeling/tasks.py", line 225, in run_tr55
    kind = kinds['reclass']
TypeError: string indices must be integers
```

**Comment by lewfish** [comment]
This was fixed in https://github.com/WikiWatershed/model-my-watershed/pull/1236 Before this fix was introduced, the frontend was sending modifications with a value of type string, which the backend cannot handle since it expects a dictionary. According to Rollbar, this bug last occurred on 7/24. On 7/29, version 1.13.0 was released which contains the above PR:
https://github.com/WikiWatershed/model-my-watershed/commit/b208983d61a9800d74da4217769d83b5bb69da9d#diff-9abeff034ba5a68b4814ee90721888ebR519
