### ISSUE TITLE
An AoI containing only water causes animal endpoint and MapShed to fail

### ISSUE THREAD

**Issue by caseypt** [WikiWatershed/model-my-watershed#1458]
Depends on #1451 

Error:

```
{"status":"failed","started":"2016-09-08T15:46:32.656Z","finished":"2016-09-08T15:46:35.535Z","result":"","error":"unsupported operand type(s) for *: 'NoneType' and 'float'","job_uuid":"d510c772-46c8-4c4e-b8b1-cf7a24b98381"}
```

To reproduce:

- Select the 1km2 AoI and click an array in a lake or ocean.
- All of the analyses should complete successfully except the animal analysis.
- Proceeding to the model page for MapShed should cause the animal analysis to retry, but it should still fail. MapShed should fail as well.

**Comment by kellyi** [comment]
Some notes:

For this AOI:

<img width="1249" alt="screen shot 2016-09-09 at 3 26 42 pm" src="https://cloud.githubusercontent.com/assets/4165523/18399990/dc4cf9a0-76a1-11e6-85d7-aebc5b65ce22.png">

The `animal_energy_units` method from MapShed performs a query which pulls this from the db:

```
population => {'sheep': None, 'horses': None, 'turkeys': None, 'layers': None, 'beef_cows': None, 'hogs': None, 'dairy_cows': None, 'broilers': None}
```

There looks to be a non-working `dictionary.get(this, or_default)` op happening, which might be failing because the check looks for whether the key exists in the dictionary rather than whether the value is of a certain type:

```
livestock_aeu = round(sum(population.get(animal, 0) *
                                  WEIGHTOF[animal] / 1000
                                  for animal in LIVESTOCK))
poultry_aeu = round(sum(population.get(animal, 0) *
                                WEIGHTOF[animal] / 1000
                                for animal in POULTRY))
```
