### ISSUE TITLE
Fix point source city name data issues

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1460]
The city names in the DRB point source data have odd or no spacing and some incorrect characters. 
![screen shot 2016-09-08 at 2 19 17 pm](https://cloud.githubusercontent.com/assets/12868342/18361316/59281afa-75cf-11e6-96ae-65bfcbaf2c0b.png)

**Comment by caseypt** [comment]
Still working through some edge cases, but here's where things are at.

I might have to clean up some things manually.

Script.

```bash
sed -Ei .bak -e 's/1TWP/ TWP/g' \
            -e 's/TWP/TOWNSHIP/g' \
            -e 's/([A-Z])(BORO)/\1 \2/g' \
            -e 's/BORO/BOROUGH/g' \
            -e 's/([A-Z])(CITY)/\1/g' \
            ./ms_pointsource_drb.sql.txt

```

Results (as a diff) are attached.
[diff.patch.txt](https://github.com/WikiWatershed/model-my-watershed/files/464773/diff.patch.txt)

**Comment by caseypt** [comment]
I removed cleaning up of boro/borough in the script because there are too many edge cases (some towns have "boro" in the name, some don't and are just organized as a borough but were included in the data as `{NAME}BORO`, for example). 

```bash
#!/bin/bash

sed -Ei .bak -e 's/1TWP/ TWP/g' \
            -e 's/TWP/TOWNSHIP/g' \
            -e 's/([A-Z])(CITY)/\1/g' \
            ./ms_pointsource_drb.sql.txt
```

After running the above script, I made the following changes manually:

- Removed "BORO/boro" from town names that do not include "boro" in their name.
- For town names structured as "Borough of {Name}boro", I changed them to just "{Name}boro".

An updated diff is attached. @ajrobbins @mmcfarland Want to take a look? 
[diff.txt](https://github.com/WikiWatershed/model-my-watershed/files/467859/diff.txt)

**Comment by ajrobbins** [comment]
I took a quick look at the diff, looks good! A couple of things:
- Can we make them all the same capitalization? It appears that there's a mix of all caps and normal proper noun capitalization
- Also, this caught my eye:
![screen shot 2016-09-12 at 3 59 27 pm](https://cloud.githubusercontent.com/assets/12868342/18450680/f9400860-7901-11e6-9a2b-8769c08434e3.png)
Does that mean that Borough of Paulsboro became Paulsboro and vice versa with this fix?

**Comment by mmcfarland** [comment]
If they're separate words, the casing can be handled in display via CSS.

**Comment by caseypt** [comment]
> Can we make them all the same capitalization? It appears that there's a mix of all caps and normal proper noun capitalization

I didn't bother to do this because we apply a "title" casing to the all of the names before displaying them. https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/analyze/templates/pointSourceTableRow.html#L2

> Does that mean that Borough of Paulsboro became Paulsboro and vice versa with this fix?

"Borough of Paulsboro" was changed to "Paulsboro". Every NJ borough is listed as "Borough of {Name}". "Borough of Paulsboro" seemed redundant (as well as "Swedesboro"), so I dropped the "Borough of " part. I can add it back if necessary.

**Comment by ajrobbins** [comment]
Ah, I see. +1 from me then

**Comment by caseypt** [comment]
I updated the source file on S3 with the cleaned-up file and ingested it locally.

Some samples from the app:

![image](https://cloud.githubusercontent.com/assets/1042475/18521079/acb101fc-7a78-11e6-9772-b23222835e3b.png)

![image](https://cloud.githubusercontent.com/assets/1042475/18521111/d73ff68a-7a78-11e6-8d96-af66a5440f20.png)
