### ISSUE TITLE
Touchscreen issues with ACER laptop

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#1500]
Reported by Stroud:
>Just got a couple videos sent to me by Nanettte. She was working with two teachers this morning in Kennett Square, PA (DRB). Their school has ACER laptops with touchscreens and Chrome as the browser. They were using a mouse but still had the following issues.
 
1.      Could not click on Overlays or Observations in the Layers menu. Could not enable any of these.

2.      Delineate watershed does not work.

**Comment by ajrobbins** [comment]
More details - teachers were running Windows and using the production site. Some of these issues may be fixed with https://github.com/WikiWatershed/model-my-watershed/pull/1454

**Comment by ajrobbins** [comment]
I just tested the production site on our ASUS windows touch test device (testing using Chrome), and I couldn't click on anything in the layer selector (including other tabs). I can double tap on the layer selector and zoom into the basemap underneath as well as drag to pan, so I think the layer selector is not registering touch events correctly and they're being captured by the basemap beneath.

**Comment by ajrobbins** [comment]
I can't reproduce the RWD issue.

**Comment by arottersman** [comment]
What we found with #1454 was that even if you're clicking, chrome will fire both touch and mouse events when its running on a touch/mouse machine like new windows laptops. 

Also, another data point, on my android phone running chrome, the same thing happens - clicking the tabs on the layer selector pans/zooms the maps instead of selecting a new tab. Maybe we should be handling touch events explicitly here https://github.com/WikiWatershed/model-my-watershed/blob/a464bd213a92e3d04080e0af26b0af65e47d4a16/src/mmw/js/src/core/layerControl.js#L285 ?
