### ISSUE TITLE
itsi_embed option doesn't handle anonymous users

### ISSUE THREAD

**Issue by scytacki** [WikiWatershed/model-my-watershed#1555]
We recently started using the `itsi_embed` option. This fixes the snapshots, but it broke anonymous access.

The problem seems to be that MMW automatically tries to log in with ITSI if the `itsi_embed` option is used.  But if the activity being used anonymously then this fails. Here is an example activity: https://authoring.concord.org/activities/5667  If you make sure you are not logged in and then run that activity, scroll to the MMW interactive and click "click here to start the interactive", you can see the issue.

There are two solutions, I can think of:
1. Don't try to auto login the user when itsi embed is used.
2. Use the lara-interactive-api to figure out if the model is being run anonymously or not.

Option 2 is better but a bit more complicated. The way you do it is:
Send the `getAuthInfo` message to LARA. This documented here: http://concord-consortium.github.io/lara-interactive-api/docs/#getauthinfo
Then wait for the `authInfo` response. The authInfo response has a `loggedIn` property. If that is false then MMW should log the user in as a guest, if it is true, then it should log the user in through ITSI.  Or if you want to make it more flexible, then MMW should use the `provider` property to figure out which provider it should try to log the user in with.  MMW should also handle the case where no response is sent after a reasonable amount of time. Perhaps 30s is good here. If no `authInfo` response is received MMW could show the usual login dialog.

**Comment by rajadain** [comment]
Hi Scott,

I've reviewed notes from a recent meeting, and done some preliminary investigation, and this is what I've found:

 * We can't query `auth/concord_id/user.json` from the Django middleware because that server doesn't know who the user is logged in as. That GET request needs the `cc_auth_token` cookie to return the right value.
 * We can't XHR `auth/concord_id/user.json` from the front-end either, because of CORS limitations
 * `getAuthInfo` will only return `loggedIn` as `true` or `false`, and doesn't tell us who the user is logged in as. 

The best we can do is, as you suggested above, disable the auto-login and use LARA to see if the user is logged in outside. If they are, we can trigger the OAuth dance. Else, we continue as guest. They can always click "Login" in the interim and log themselves in.

The tricky part is going to be dealing with saved state. Imagine the following scenario:

 * Logged in user opens activity.
 * LARA communicates the last saved URL (via `loadInteractive`), which is a private project belonging to the user
 * The project is not visible because the user isn't logged in yet
 * We do the redirect dance to log the user in, but they come back to the home page instead of the project
 * They are not taken to their original project

This _could_ be solved if we could hold off loading saved state until _after_ the user has logged in. Is there a way for us to request a `loadInteractive` call from the parent?

This could still be disruptive if the auto-login takes up to 30s, but we'll figure out how to deal with that delay when we get to that point.
