### ISSUE TITLE
No site stormwater model results near Aspen, CO

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1611]
User reported errors of Site Stormwater failing to return results for a watershed near Aspen, CO - specifically the `Woody Creek` HUC12 boundary.

https://app.wikiwatershed.org/project/5315/scenario/12136

Specfically, there is a JS error when trying to access the runoff results, which are empty:
```json
    "runoff": {},
    "quality": []
```

Visually, the only thing out of the ordinary is a substantial gap in the soils data - though this is not unique to this area, and is quite common in urban areas that are heavily tested (the soil `NODATA` should be getting filled in with a default).

![screenshot from 2016-11-14 12 24 25](https://cloud.githubusercontent.com/assets/1014341/20275122/4e37bdd8-aa65-11e6-8595-5a093d4a609c.png)

**Comment by mmcfarland** [comment]
Neighboring HUC12s with similar gaps in data execute the model correctly.

**Comment by arottersman** [comment]
From `debugcelery`
`[2016-11-14 13:49:27,470: ERROR/Worker-1] Bad input data to TR55: u'Unknown land use: perennial_ice'`

Seems like `perennial_ice` was taken out here (https://github.com/lliss/tr-55/blob/fa4485762bce30473aad957675f30c610ae3753b/tr55/tables.py#L385) because it wasn't supported https://github.com/WikiWatershed/tr-55/pull/43#issuecomment-141191809

**Comment by mmcfarland** [comment]
Good find - I'll reach out to find out if coefficients can be provided for perennial ice or if we should disregard land use of that type.
