### ISSUE TITLE
Investigate RWD timeouts on staging

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#1707]
> DRB RWD on staging seems to be failing and not generating useful errors or logs.

**Comment by kdeloach** [comment]
We're able to transfer data at a rate of ~3.5MB/s from S3 to our workers using the `r4.large` EC2 instance type. As a result, it takes about 6 hours to download the DRB `Main_Watershed` shapefiles (78GB) to each worker instance. Since we provision our staging environment daily (or multiple times per day) this can lead to timeouts.

**Comment by ajrobbins** [comment]
We'll be addressing this by having three workers up full-time

**Comment by hectcastro** [comment]
I had a discussion with Matt about this and we would like to:

- Keep staging as is (scale up to 2 and down to 0)
- Adjust production so that it remains at a constant 2

The scheduled scaling adjustments were done when we were using smaller instances. Now that we are using larger instance types, it makes sense to keep the worker count constant (which helps increase the probability that DRB data stays warm).

I already made the necessary adjustments for the next scheduled deployment.

**Comment by mmcfarland** [comment]
Our scaling policy, EBS warm up script and VPC endpoint changes have been effective in mitigating this issue.
