### ISSUE TITLE
Evaluate size and timeout thresholds

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1746]
We currently prevent results showing for both analyze and models by restricting on size or failing a poll after a timeout.  Now that we are generating potentially very large watersheds through RWD, some are small enough to pass the size limitation to proceed to analyze but large enough that they fail to return results before the timeout. 

Staging servers are provisioned with workers machines that are identical to Production.  Determine what threshold is more appropriate for those shapes.

**Comment by arottersman** [comment]
Currently the max AOI size is set to 112,845 km^2 for Analyze/TR-55 and 1000 km^2 for MapShed. The task timeout is set at 45 sec. 

I've been clicking around with the Continental RWD tool, and have found that the limit for TR-55 before it times out is generally around 36,000 – 60,000 km^2 when modeling the delineated watersheds. The limit exists as a range because some watersheds have fewer vertices. If I draw a simple shape free hand the max model-able size is ~70,000 km^2.

When TR-55 times out it is likely the land and soil analyze tabs will timeout as well, though the other analyze tabs always continue to work just fine.

We could proceed in a number of ways:
1. Just as we set a limit on MapShed, choose a threshold for TR-55 based only on area. This could be ~70,000 (most optimistic) for drawn shapes, and ~60,000 for RWD shapes
2. Set a threshold on TR-55 as a function of # of points and area. This has the advantage of not singling RWD out; the upload-a-shapefile feature could end up with the same large, complex-shape timeout issues
3. Lower the max area threshold and simplify shapes before they go into model mode

**Comment by arottersman** [comment]
On even further inspection, I don't think the number of vertices is all that related to the timeouts. 

Here's an RWD shape with ~500 vertices:
https://staging.app.wikiwatershed.org/project/742/scenario/1407

Here's a shape I drew to recreate it with about 7 vertices,
https://staging.app.wikiwatershed.org/project/753/scenario/1429

They both fail. The drawn shape is only 40,000 km^2. I thought it might be related to the land and soil cover, but this [shape](https://staging.app.wikiwatershed.org/project/743/scenario/1409) succeeds. It is of similar size, and directly south of the two failing shapes with similar land/soil cover.

At @rajadain 's suggestion I am now going to test these out on my local to see where they get hung up.

**Comment by arottersman** [comment]
@rajadain helped me investigate this some more this morning.

The underlying operation timing out is the `mmw-geoprocessing` `SummaryJob`, which reads NLCD and Soil tiles from S3 and uses them to calculate the AOI's land/soil histograms. We found that the calculation doesn't take much time compared to fetching the tiles. It seemed a shape requiring twice as many tiles as another would take twice as long, regardless of AOI area. We, therefore, need to make the threshold based on the number tiles we anticipate will be fetched.

The number of tiles fetched depends not on the AOI's area, but on its [bounding box's](https://github.com/WikiWatershed/mmw-geoprocessing/blob/develop/summary/src/main/scala/SummaryJob.scala#L37) area.

For example see how this diagonal shape times out:
![screen shot 2017-04-07 at 2 58 27 pm](https://cloud.githubusercontent.com/assets/7633670/24815317/b658f1bc-1ba2-11e7-9242-dc173419faff.png)

But two similar, non-diagonal shapes succeed despite larger areas:
![screen shot 2017-04-07 at 2 31 46 pm](https://cloud.githubusercontent.com/assets/7633670/24815208/6e8ff9e8-1ba2-11e7-8af7-f7832f0cd684.png)

![screen shot 2017-04-07 at 2 40 26 pm](https://cloud.githubusercontent.com/assets/7633670/24815210/6e94ce14-1ba2-11e7-955e-2835acee1854.png)

The diagonal shape has a large bounding box and pulls in many more tiles.
