### ISSUE TITLE
Tool tip helps with links

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1749]
We've been unable to add links to the help tooltips since they persist only on hover (and likewise difficult to take a screenshot of for this issue).

Update the usage of the library (or provide an alternative) so that links can be clicked within the tooltip.  Keep in mind that the draw tools will be moved in #1735.  The other usage is as legends in the new layer selector.

**Comment by kellyi** [comment]
Shares a point with #1747

**Comment by arottersman** [comment]
- Are there actual links that should go into the app with this card? 
----
- It seems to make a link clickable on these popovers while still making them show on hover we'd have to have the tooltip/popover also count as a hover target, ie the element closes if you leave either the original tooltip icon, OR the tooltip itself. That way you could very carefully move your mouse over to the tooltip to click the link
- Another very easy alternative is just to change the tooltips to show/hide on `click` instead of `hover`, which I assume already happens for mobile

Which would be preferred?

**Comment by mmcfarland** [comment]
I think my preference would be for click, unless "careful" was actually pretty generous while moving the mouse.

We do have actual links that were suggested to us, I'll try to dig them up.

**Comment by mmcfarland** [comment]
Original request:
> Add the following text and link to the bottom of help text in all of the "?" help balloons.
"Info and help for these tools at http://wikiwatershed.org/model/"

**Comment by arottersman** [comment]
Putting this back in the queue because it seems pretty dependent on how https://github.com/WikiWatershed/model-my-watershed/pull/1778 turns out.

Also found https://github.com/WikiWatershed/model-my-watershed/issues/1233 for more links we can add.

**Comment by ajrobbins** [comment]
I asked @aufdenkampe for text for links, but we likely wont have it for another week or so.
