### ISSUE TITLE
Ingest soilpallland2 raster

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1751]
Ingest new raster provided as `soilpallland2`.

Ensure that projection, extent & grid size are compatible with our other layers if this layer is to be used in conjunction with them.

**Comment by arottersman** [comment]
Swapped out of queue for #1793 and #1787

**Comment by mmcfarland** [comment]
For reference, extent and projection should match our other ingests and use the smallest datatype appropriate for the values.

```
CRS=EPSG:5070
LAYOUT_EXTENT=-2493045.000,177285.000,2342655.000,3310005.000
```

**Comment by arottersman** [comment]
Ingest complete. Results in `s3://datahub-catalogs-us-east-1/soilpalland2_5070`

[Here's](https://github.com/azavea/civic-apps-etl/tree/arr/soilpalland) the branch on `civic-apps-etl`. See https://github.com/azavea/civic-apps-etl/commit/d8bf566477526afadda7d173aa0a82c303c33ca1 for specifics.

#### Special Steps/Mutations before actual ingest:
- Perhaps because the raster was so coarse, when I tried to chunk it with pixel size 3096 (what we usually use), it only created two tiles and the local ingest ran out of memory. I adjusted the spark executor memory, the driver memory, and the number of partitions, but still couldn't get it to work. Then adjusted the pixel size to the default 256, which created ~200 chunks, and the ingest completed.

- When I tried to ingest the original raster untouched there were `osgeo.ProjectionExceptions`. This could be because there's no projection set on the original. I used `gdal_warp` to set it to EPSG:5070, which is what we want it to output as anyway.

```bash
gdalwarp -overwrite -t_srs EPSG:5070  -of GTiff \
            civicapps-etl/raw/soilpalland2.tif \
            civicapps-etl/raw/soilpallland2_5070.tif
```

- (Then chunked it again.)

**Comment by arottersman** [comment]
I think these got created as `Int16` (their type in the original). Should they instead be `Int8`s?

**Comment by mmcfarland** [comment]
> Should they instead be Int8s?

Only if the source data would be contained, I don't have access to the tif at the moment so I can't check the range, but a `gdalinfo soilpalllad2_5070.tif -stats` would give you the right min/max.  I'm assuming `Int16` is appropriate.

Looks like there's a typo in the bucket name in s3, if the contents are small - it may make sense to move it to a correctly named bucket no avoid confusion in the future.

**Comment by arottersman** [comment]
`Min=49.000 Max=5280.000`, so looks like we're good with `Int16`. I've moved `soilpalland2_5070` to `soilpallland2_5070`. Thanks for catching that!
