### ISSUE TITLE
Map components are visible under sidebar when app is loading

### ISSUE THREAD

**Issue by caseycesari** [WikiWatershed/model-my-watershed#1773]
The map controls and attribution appear on top of the sidebar while the app is loading. I believe this is because the sidebar doesn't have a background color set, and the map is initially sized to the full width of the page.

![mmw4](https://cloud.githubusercontent.com/assets/1042475/24310539/b239b32a-10a6-11e7-8085-31a6c23404ab.gif)

**Comment by rajadain** [comment]
This is likely because of the fact that we use absolute positioning for the map, and pull it back with a value of [`right: 485px`](https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/sass/base/_map.scss#L43). The `.sidebar` component has full width and `0` height in practice, and the contents are just floating in empty space. We see the same behavior on the Bees application: https://pollinator-modeling-app.azavea.com/

I think a solution to this will be to rearchitect the front-end to use a hierarchy of nested divs with relative positioning, rather than a flat structure with absolute positioning. But such a rearchitecture is probably more than 1 point, and may need some **#design** support.
