### ISSUE TITLE
Save project workflow; Add save button

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#1860]
The app will no longer save automatically. Add a save button with three states: "Save", "Saving", "Saved"
![screen shot 2017-05-04 at 11 44 24 am](https://cloud.githubusercontent.com/assets/7633670/25712275/3391f378-30bf-11e7-9f59-4b56cde8b897.png)
![screen shot 2017-05-04 at 11 44 34 am](https://cloud.githubusercontent.com/assets/7633670/25712274/3390c26e-30bf-11e7-8c09-67226cc78934.png)
![screen shot 2017-05-04 at 11 44 29 am](https://cloud.githubusercontent.com/assets/7633670/25712276/3392ee4a-30bf-11e7-9bb8-7e9650b8bd0f.png)

Show regular login modal when a guest user tries to save. We'll implement the new prompt in #1861

**Comment by arottersman** [comment]
@jfrankl
Should save *only* ever happen when you click save? Some actions/behaviors in particular I'm wondering about:

- Naming the project
- Having already saved the project, autosaving modifications
- Naming a scenario

**Comment by jfrankl** [comment]
Below is my understanding of the new save functionality. Would like confirmation from @ajrobbins and/or @mmcfarland.

- The initial save only happens when you click save
- After the initial save, autosaving begins on any changes ("Saved" changes to "Saving" to indicate that automatic saving is happening. Then returns to "Saved" when save is complete)
- Attempting to navigate away from your project before the project is saved will trigger an alert ("Do you want to leave this site? [Stay] [Leave]"), see wireframes

I don't think any actions except clicking the "Save" button should trigger a save. As an enhancement, I could imagine giving the user a reminder to save when they name their project, make 10 modifications without saving, etc.
