### ISSUE TITLE
Ingest Precip and Temp rasters

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#1905]
Ingest climate data rasters for use in analysis.  These are coarse rasters and don't need to be resampled to match the resolution of the ones used in the models, but they should be reprojected to 5070.

**Comment by ajrobbins** [comment]
Rasters are here: https://drive.google.com/drive/folders/0B2fuZWlhXcqQd1ZDWE1wUEt0a0U?usp=sharing

**Comment by mmcfarland** [comment]
The ppt are also already downloaded and on the fileshare.

**Comment by arottersman** [comment]
Tiles are at `s3://azavea-datahub/catalog/climatology-epsg5070`, where `s3://azavea-datahub/catalog/climatology-epsg5070/ppt/01` would have the precipitation tiles for January, and `s3://azavea-datahub/catalog/climatology-epsg5070/tmean/04` would have the tmean tiles for April.

Original rasters are now at `s3://azavea-datahub/raw/climatology`. They were too small to chunk. The ingest was done with [this script](https://github.com/azavea/civic-apps-etl/blob/arr/bigcz-climatology/ingest_climatology.sh). 

Because the rasters are so coarse (cell size is about 110,000m), we set the tile size to 512 x 512. We tried to use as high as 1024, but ended up with one 1.1MB tile and five tiles ~4-400kb.

**Comment by rajadain** [comment]
Imported climate rasters from GeoTrellis account to the Azavea Datahub, and updated the `metadata_*.json` files to reflect the new structure. They are now available to the geoprocessing service as:

 * `climatology-epsg5070-ppt-01`
 * `climatology-epsg5070-ppt-02`
 * `climatology-epsg5070-ppt-03`
 * `climatology-epsg5070-ppt-04`
 * `climatology-epsg5070-ppt-05`
 * `climatology-epsg5070-ppt-06`
 * `climatology-epsg5070-ppt-07`
 * `climatology-epsg5070-ppt-08`
 * `climatology-epsg5070-ppt-09`
 * `climatology-epsg5070-ppt-10`
 * `climatology-epsg5070-ppt-11`
 * `climatology-epsg5070-ppt-12`
 * `climatology-epsg5070-tmean-01`
 * `climatology-epsg5070-tmean-02`
 * `climatology-epsg5070-tmean-03`
 * `climatology-epsg5070-tmean-04`
 * `climatology-epsg5070-tmean-05`
 * `climatology-epsg5070-tmean-06`
 * `climatology-epsg5070-tmean-07`
 * `climatology-epsg5070-tmean-08`
 * `climatology-epsg5070-tmean-09`
 * `climatology-epsg5070-tmean-10`
 * `climatology-epsg5070-tmean-11`
 * `climatology-epsg5070-tmean-12`
