### ISSUE TITLE
Link CINERGI Results to Main Website

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#2140]
CINERGI results to link to its detail page in the original CINERGI website. The URL can be composed as:

```
{{ cinergi_host }}/geoportal/?filter="{{ result._source.fileid }}"
```

e.g. http://cinergi.sdsc.edu/geoportal/?filter=%220ba7a5a0-fcf0-402c-853c-7dc8751ea8b5%22

Note the quotes around the filter parameter, which are necessary to make it work. These links should open in a new window, just as CUAHSI / WDC links do.

**Comment by ajrobbins** [comment]
Need to consult @jfrankl about how this link should look/where it should be placed. One of these buttons on the detail page is an option:

![screen shot 2017-08-10 at 1 42 44 pm](https://user-images.githubusercontent.com/12868342/29183822-057a4642-7dd2-11e7-9ac4-1e7ff077ed8d.png)

But since it's just one link, perhaps a small external link icon placed elsewhere on the detail page would be more appropriate.

**Comment by arottersman** [comment]
Shares a point with #2141

**Comment by jfrankl** [comment]
@ajrobbins I think one of those buttons would be a great spot for that link.

**Comment by rajadain** [comment]
Depends on #1934
