### ISSUE TITLE
WDC results are not added to map in some scenarios

### ISSUE THREAD

**Issue by caseycesari** [WikiWatershed/model-my-watershed#2151]
To reproduce:

- Draw an AoI roughly around the John Heinz Wildlife Refuge (just northwest of the airport).
![image](https://user-images.githubusercontent.com/1042475/29332982-0850c722-81d0-11e7-8f9d-c8cb2e644ff8.png)

- Search for "hydrogeology".
- Switch to the WDC tab. Note that when the search completes there should be approximately three results in the JSON response. The number of results will also be noted in the WDC tab. However, no results are shown in the list or on the map.

![image](https://user-images.githubusercontent.com/1042475/29333030-3f776a80-81d0-11e7-9220-fc3457b95639.png)

Sample JSON response:

```json
[{
	"catalog": "cuahsi",
	"api_url": null,
	"results": [{
		"id": "NWISGW:395327075164201",
		"title": "DE   510",
		"description": "The USGS National Water Information System (NWIS) provides access to millions of sites measuring streamflow, groundwater levels, and water quality. This web service provides methods for retrieving Ground Water data from NWIS. For more information about NWIS, see the NWIS home page at http://waterdata.usgs.gov/nwis",
		"author": null,
		"links": [{
			"href": "http://hiscentral.cuahsi.org/pub_network.aspx?n=8",
			"type": "service"
		}],
		"created_at": "1946-11-08T00:00:00Z",
		"updated_at": null,
		"geom": {
			"type": "Point",
			"coordinates": [-75.2779627, 39.89066835]
		},
		"details_url": null,
		"sample_mediums": "Groundwater",
		"concept_keywords": "Groundwater level",
		"service_org": "U.S. Geological Survey (USGS)",
		"service_code": "NWISGW",
		"service_url": "http://hiscentral.cuahsi.org/pub_network.aspx?n=8",
		"begin_date": "1946-11-08T00:00:00Z",
		"end_date": "1946-11-08T00:00:00Z"
	}, {
		"id": "NWISGW:395326075164501",
		"title": "DE   511",
		"description": "The USGS National Water Information System (NWIS) provides access to millions of sites measuring streamflow, groundwater levels, and water quality. This web service provides methods for retrieving Ground Water data from NWIS. For more information about NWIS, see the NWIS home page at http://waterdata.usgs.gov/nwis",
		"author": null,
		"links": [{
			"href": "http://hiscentral.cuahsi.org/pub_network.aspx?n=8",
			"type": "service"
		}],
		"created_at": "1946-08-29T00:00:00Z",
		"updated_at": null,
		"geom": {
			"type": "Point",
			"coordinates": [-75.2779627, 39.89066835]
		},
		"details_url": null,
		"sample_mediums": "Groundwater",
		"concept_keywords": "Groundwater level",
		"service_org": "U.S. Geological Survey (USGS)",
		"service_code": "NWISGW",
		"service_url": "http://hiscentral.cuahsi.org/pub_network.aspx?n=8",
		"begin_date": "1946-08-29T00:00:00Z",
		"end_date": "1946-08-29T00:00:00Z"
	}],
	"count": 2,
	"page": null,
	"previous": null,
	"next": null
}]
```

**Comment by arottersman** [comment]
We filter out the results because they don't intersect with the AOI (but are in the bbox). 
![screen shot 2017-08-30 at 1 41 57 pm](https://user-images.githubusercontent.com/7633670/29886701-05d98794-8d89-11e7-8a6a-04f8e4cdf66d.png)

The fix for this card should be to correct the count, which is set before the filter. Is that right,  @rajadain?

**Comment by rajadain** [comment]
> The fix for this card should be to correct the count, which is set before the filter.

Yes that is correct. Initially the shown count did reflect the number of shown results, instead of the API's value. This was changed in #2067, because we wanted to indicate how many total results there were for the query, and we wouldn't know how many would be filtered out in later pages until those pages were loaded, so we couldn't give an accurate count of filtered results.

For WDC, which has no pages, we should use the filtered number. Perhaps optionally (or perhaps for a later card), we can do the same for CINERGI and HydroShare when there is only one page of results.
