### ISSUE TITLE
IE11: Analyze Tab In Model Shows Model Results

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#2276]
The analyze/model toggle on the model page doesn't actually toggle the view in IE11. No console errors that I saw.
<img width="962" alt="screen shot 2017-09-20 at 4 25 55 pm" src="https://user-images.githubusercontent.com/7633670/30666063-2bc2e772-9e21-11e7-8a03-5ac302db570a.png">

**Comment by kellyi** [comment]
This is happening because toggling the "Analyze" and "Model" tabs in IE11 doesn't properly change the `.active` class on the `#modeling-tab-contents` and `#analyze-tab-contents` divs. I manually changed them in the developer tools and got the desired output:

![screen shot 2017-10-09 at 10 25 27 am](https://user-images.githubusercontent.com/4165523/31343028-7c3b2614-acdc-11e7-88be-62b437869eea.png)

![screen shot 2017-10-09 at 10 25 47 am](https://user-images.githubusercontent.com/4165523/31343033-7f9377bc-acdc-11e7-8746-0994bf79fb5d.png)

Since the modeling tab is the default for IE11, it starts with the `.active` class & then that's never relinquished. Going to check the toggle code to see what adjustment to make.
