### ISSUE TITLE
Capture DRB user location information

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2330]
Stroud would like to isolate and allow for pulling user data for users in the DRB, since that's a major area of funding and focus of MMW.

In https://github.com/WikiWatershed/model-my-watershed/issues/2255#issue-257734300, we'll be adding more fields to the user onboarding modal, including one for ZIP codes. 
~~We should:~~
~~- Generate list of ZIP codes that intersect the DRB and create a lookup table~~
~~- When a user creates a new account, check the inputed ZIP against said table~~
~~- If the ZIP is a match, stamp that user account record in the DB so it can be queried for later~~

Create a management command that pulls DRB user info out into a csv.

**Comment by rajadain** [comment]
It may be more efficient to simply use a list of zip codes when querying the users to find out which ones are in the DRB, rather than adding this information in the database. If we can get a list of ZIP codes in the DRB, we can construct a query that gets the user details for those users.

Here is a shapefile of all ZIP codes in the United States: https://catalog.data.gov/dataset/tiger-line-shapefile-2015-2010-nation-u-s-2010-census-5-digit-zip-code-tabulation-area-zcta5-na

Here is a GeoJSON of the DRB used in the app: https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/mmw/settings/data/drb_perimeter.json

If a list of matching ZIPs is posted here, I will post the relevant SQL query.

**Comment by ajrobbins** [comment]
List of matching zips:
[zip2.csv.txt](https://github.com/WikiWatershed/model-my-watershed/files/1455542/zip2.csv.txt)

Produced by intersecting the [TIGER/Line 2017 zip data](https://www.census.gov/cgi-bin/geo/shapefiles/index.php?year=2017&layergroup=ZIP+Code+Tabulation+Areas) with the [DRB shape](https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/mmw/settings/data/drb_perimeter.json).
