### ISSUE TITLE
Change color of BiG CZ point results

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2337]
Currently, the default blue used for point results:

![screen shot 2017-10-05 at 2 40 35 pm](https://user-images.githubusercontent.com/12868342/31246383-3e422e92-a9db-11e7-9259-819bf9a99460.png)

Is extremely similar to the styling of the observations USGS points:

![screen shot 2017-10-05 at 2 40 56 pm](https://user-images.githubusercontent.com/12868342/31246436-67c3ed0a-a9db-11e7-93e6-dca32e734401.png)

Which is confusing visually. @jfrankl thoughts?

**Comment by jfrankl** [comment]
I suggest that we should change the color for Observations USGS points, because I see those layers as a secondary feature to the application and I think we can be more flexible with coloring them. How about some kind of yellow like this?

![image](https://user-images.githubusercontent.com/1809908/31618592-5c332c8e-b260-11e7-8628-2ad4d25c8b3d.png)
