### ISSUE TITLE
Evaluate AWS reservations potential

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2370]
Evaluate the potential areas of the MMW staging/prod AWS infrastructure in which reservations could be used to reduce cost, and develop recommendations for implementation.

**Comment by mmcfarland** [comment]
I'd like to be included on this evaluation.  Some related things to consider that may have an impact on reservation perspective:

* Are we over-provisioned with App/Tile servers?
* Using a new instance type for our Workers which have more CPUs

**Comment by hectcastro** [comment]
First some environment specific issues based on AWS billing data:

## Production

- Monitoring instance consistently expensive
  - Disabled `logstash-web`, which was eating all CPU
  - Everything still works with it disabled; unused component
  - Decreased instance type

## Staging

- Monitoring instance consistently expensive
  - Disabled `logstash-web`, which was eating all CPU
  - Everything still works with it disabled; unused component
  - Decreased instance type
- Cleared out unused AMIs and EBS snapshots
- Multi-AZ mode for RDS disabled

---

Then, some more service specific issues:

## General

- Buy RIs for EC2, ElastiCache, RDS

## App

- Determine if instance type can be dropped from `t2.medium`
  - Fix issues with failing instances
- ASG goes up to 4x during peak hours

## Tile

- Instance type recently dropped from `t2.medium` to `t2.small`
- ASG goes up to 4x during peak hours

## Worker

- RIs
- Determine if instance type can be changed (expensive effort-wise)

**Comment by mmcfarland** [comment]
### General
* All those changes look succesful
* RIs make sense for units in the `t2` family and our RDS/ElasticCache instances across environments.  Since client is billed directly, they may be limited in the up front payments required.  If we had a ball-park estimate of savings, @ajrobbins may be able to see if there is an appetite.

### App
* Concern about using `t2.small` with BigCZ serialization issue potential seems to have been unwarranted.  I think we can indeed pull down from the `t2.medium` in use.
* Likewise, I think it's probably safe to try running 3 instances in peak hours
* Problematic python imports are behaving well under the "scoped import" approach used in triage.bbbbbu

### Tile
* Smaller instance type is handling load well, but utilizing enough that 4 seems to be a fine number for now.

### Worker
* Let's keep as is, since they're working well, and potentially use the savings gathered elsewhere to add a 3rd instance in prd.

**Comment by ajrobbins** [comment]
>Since client is billed directly, they may be limited in the up front payments required. If we had a ball-park estimate of savings, @ajrobbins may be able to see if there is an appetite.

Agreed, I think we need to be able to show them a ballpark savings estimate, or a ballpark upfront cost estimate at the very least for them to make the decision.

**Comment by hectcastro** [comment]
I broke down just the EC2 resources below because I think that is where most of the cost savings can come from (RDS is second, but there are some new wrinkles around RDS RIs that I'm unfamiliar with). All RIs below are no-upfront. That means they don't have to pay anything upfront, they just get a reduced hourly rate for the next 12 months (your hourly rate can go lower if you opt to put more money upfront).

**Note**: Units here are based on the smallest instance type for each instance family (`t2.nano` is smallest for T2, `r4.large` is smallest for R4), and the normalization factor is outlined in: https://aws.amazon.com/blogs/aws/new-instance-size-flexibility-for-ec2-reserved-instances/

## EC2

### Staging

#### T2 (4 tile + 4 app + 4 NAT + 4 bastion = 16 units)

- $51 on-demand
- $32 RIs

#### R4 (2 units)

- $1168 on-demand
- $735 RIs

### Production

#### T2 (8 tile + 16 app + 4 NAT + 4 bastion = 32 units)

- $136 on-demand
- $85 RI

#### R4 (2 units)

- $1168 on-demand
- $735 RIs

---

Total on-demand: $2523
Total w/ RIs: $1587

**Comment by ajrobbins** [comment]
This is great! I'll bring this up with the client, and emphasize that these numbers are not set in stone.

**Comment by hectcastro** [comment]
I decreased the application server ASG from 4 -> 3 and updated the instance type from `t2.medium` -> `t2.small`. Charges were persisted in the infrastructure configuration file.

cc: @tnation14

**Comment by ajrobbins** [comment]
@hectcastro are the price estimates listed above for each instance family reflective of the quantities? For example, $1168 on-demand for R4 (2 units) - is that for the two units or one?

**Comment by hectcastro** [comment]
I think I did a bad job in how I presented this initially.

The $1168 is per `r4.large` for the year, which means 2 of them at on-demand pricing is $194.72/month * 12 = $2336.64 (this divided by 2 is $1168.32). The same `r4.large` with a no upfront reservation is $122.64/month * 12 = $1471.68 (this divided by 2 is $735.84).

I updated the comment above to reflect the per unit, per timeframe pricing. I then expanded the totals so that they show more of the math behind what led to them.
