### ISSUE TITLE
Investigate whether we need to return the CSRF token explicitly in views

### ISSUE THREAD

**Issue by caseycesari** [WikiWatershed/model-my-watershed#239]
We are currently doing this in `home` and `model`, but since we have the CSRFMiddleware turned on, we shouldn't need to. @lliss and I ran into problems implementing the login functionality that prompted us to do this.

See https://github.com/WikiWatershed/model-my-watershed/pull/230#discussion_r31259054

**Comment by rajadain** [comment]
Removed manually setting CSRF in Django views, confirmed that the `csrftoken` cookie is still set on each page reload and that XHR functionality such as login and logout work correctly. Ran all tests which also passed.

Should I create a pull request or stop since this issue only asked for investigation?

**Comment by ajrobbins** [comment]
Investigation concluded with https://github.com/WikiWatershed/model-my-watershed/issues/239#issuecomment-108492830, closing.
