### ISSUE TITLE
Implement revised CINERGI result card

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2392]
Currently looks like:
![screen shot 2017-10-19 at 10 58 04 am](https://user-images.githubusercontent.com/12868342/31777595-662714b8-b4bc-11e7-9d03-94da4dead963.png)

Waiting for mockup from Anthony + Emilio.

**Comment by emiliom** [comment]
Final mockup is here: https://docs.google.com/document/d/1NzDzEQ9a0cW3aEDRtrS9tHxazYsq6ScaYsnKOf7S3mw/edit

Anthony and I went over this, so it's good to go. Let me know if you have any questions. I realize the "code" at the bottom may be a bit tricky to understand.

Also referencing this old CINERGI issue, #1929. Please close it once this and the Detail View (#2393) are implemented.

**Comment by rajadain** [comment]
Hi @emiliom, here are some questions regarding this:

 1. A number of results have `1/1/1900` as the `timeperiod_nst` value:

    ![screen shot 2017-10-24 at 3 34 06 pm](https://user-images.githubusercontent.com/7633670/31964199-47e0869c-b8d1-11e7-8d17-ff9da709b404.png)

    Should these be shown as is or should there be any special treatment?

 2. There are a number of results with `ScienceBased_processed` as the source name:

    ![screen shot 2017-10-24 at 3 53 13 pm](https://user-images.githubusercontent.com/7633670/31965072-21972f7e-b8d4-11e7-8c05-9f30bfae451b.png)

    Should these have any special treatment?

 3. When the source organization name is too long, should it be `...`'d like the first line, or wrapped like the categories?

    ![image](https://user-images.githubusercontent.com/1430060/32058006-dccad9a4-ba36-11e7-92fa-1f16d45f8096.png)

**Comment by emiliom** [comment]
1: keep as is
2: no special treatment
3: ....'d


On Oct 26, 2017 7:27 AM, "Terence Tuhinanshu" <notifications@github.com>
wrote:

Hi @emiliom <https://github.com/emiliom>, here are some questions regarding
this:

   1.

   A number of results have 1/1/1900 as the timeperiod_nst value:

   [image: screen shot 2017-10-24 at 3 34 06 pm]
   <https://user-images.githubusercontent.com/7633670/31964199-47e0869c-b8d1-11e7-8d17-ff9da709b404.png>

   Should these be shown as is or should there be any special treatment?
   2.

   There are a number of results with ScienceBased_processed as the source
   name:

   [image: screen shot 2017-10-24 at 3 53 13 pm]
   <https://user-images.githubusercontent.com/7633670/31965072-21972f7e-b8d4-11e7-8c05-9f30bfae451b.png>

   Should these have any special treatment?
   3.

   When the source organization name is too long, should it be ...'d like
   the first line, or wrapped like the categories?

   [image: image]
   <https://user-images.githubusercontent.com/1430060/32058006-dccad9a4-ba36-11e7-92fa-1f16d45f8096.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/WikiWatershed/model-my-watershed/issues/2392#issuecomment-339684189>,
or mute the thread
