### ISSUE TITLE
Add new capability to download search results cards as JSON file

### ISSUE THREAD

**Issue by emiliom** [WikiWatershed/model-my-watershed#2412]
It would be very helpful to users to allow a download of the search results into a JSON file. This file can be simply the internal JSON-like data object populated by the portal after a search. Ideally the downloaded JSON file would also contain the geospatial points or bounding box geometries.

@aufdenkampe and I think this may be relatively straightforward to develop given that the portal search results are already managed "internally" as a JSON-like data structure (right?).

**Comment by ajrobbins** [comment]
This would be relatively straightforward - implementing it will just be a question of time/resources post-release. Thanks for adding the appropriate label and milestone!

**Comment by rajadain** [comment]
Hi @emiliom, for the WDC tab, when the values for some variables have been fetched by going to the detail view, would you like them to be included in the JSON download? They currently are, but can be numerous, making the downloaded file heavy but more importantly uneven, because some variables will have values and others will not. However, it is data that has been fetched and is readily available on the client side.

I'm inclined to keep it in, but wanted to confirm with you. What do you think?

**Comment by emiliom** [comment]
Hmm. My initial thinking was that the download would only include metadata, not data. 

My intent in suggesting this capability is for users to have a record of the search results that can be leveraged externally via code for follow-up work. eg, a user could read the JSON file and use ulmo to issue data (get_values) requests to any of the WDC services included in the JSON; or probe the metadata from detailed search results across catalogs, to refine a search with more flexibility.

SO, while some users would definitely benefit from being able to download that data, my vote would be for keeping things simpler and more even (consistent) at this stage and not include the data in the downloaded JSON.

I'll ping @aufdenkampe in case he wants to chime in, but I know he's pretty hammered today.

**Comment by rajadain** [comment]
Very well, I'll remove it for now. Thanks!
