### ISSUE TITLE
RWD /watershed endpoint should return valid analyze shape

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#2449]
Using the Geoprocessing API, one can generate a `/watershed` which returns as a geoJson FeatureCollection object (within the overall payload).  Copying the geoJson result into an analysis API request returns the error:

```
{
  "detail": "Area of interest must be valid GeoJSON"
}

```

The ideal workflow would be for API consumers to generate watersheds and immediately use that geometry in subsequent calls (such as how the application behaves).

Determine if either the validation on `/analyze` endpoints is too strict, or if `/watershed` should return a different format

**Comment by arottersman** [comment]
How copiable does the result need to be? We currently don't support feature collections because of the way we [parse geometries from the payload](https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/apps/modeling/geoprocessing.py#L137). We could easily grab the geometry of the collection's first feature, and use that.

RWD, however, gives back a result of the form:
```
{
    "watershed": { <FeatureCollection> },
    "input_pt": { <FeatureCollection> }
}
```
So any api users will have to access (or copy) the contents of `result.watershed`. Would it be worth it to have RWD return a single feature collection, with one feature being the watershed and the other the input_pt, and then parsing for the first feature with type `Polygon`? Or, is it fine to just accept a feature collection and expect the api user to copy the contents of `"watershed"`?

/cc @mmcfarland @ajrobbins

**Comment by mmcfarland** [comment]
Being able to programmatically access an attribute is fine (I was doing that manually in my testing), the issue is more that `result.watershed` is not valid input to any of the other geometry based calls. Is it necessary for the /watershed endpoint to return a feature collection and not a multipolygon?

**Comment by arottersman** [comment]
I don't think we use the FeatureCollection properties for anything, but I suppose someone might?

```
"properties": {
            "Avgslp": 0.044611662626266,
            "BasinLen": 0.265826812744141,
            "RR": 0.012108777649701,
            "Area": 0.014311335,
            "AvgOLF": 0,
            "DrnDen": 0,
            "BR": 3.218837738037109,
            "Strord": 1,
            "StrLen": 0,
            "GRIDCODE": 1
          }
```

**Comment by arottersman** [comment]
If we want to keep those properties, I think something like this would suffice? https://github.com/WikiWatershed/model-my-watershed/commit/8dd2cef894bc7e8a1e6f147b86404872ba8d9d31#diff-6e8ad15dd79fadadc23fdffb1a448700R146

**Comment by mmcfarland** [comment]
Yes, we should keep those properties.  I think grabbing the first feature of a FeatureCollection is adequate, but would be more ideal if `/watershed` didn't return a feature collection of one feature to begin with.  I'm still curious if it's possible to adjust that output to be a multipolygon.

My reasoning is, aside from potential documentation that may be neglected, it's not intuitive that an API user would send a FeatureCollection of several features and have only the first feature used.  We do something similar in the App with shapefile uploads, but we're able to visually indicate to the user of what just happened in a way that we aren't able to in an API.  Additionally, the shapefile format was specifically requested and by nature can contain multiple fields.  Since we control the API geometry input/output formats, we should be able to confine them to single geometries, since that's what the API operates on.
