### ISSUE TITLE
Tabbing doesn't work correctly in Safari for profile form

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2461]
In Chrome, tabbing works as expected for the new profile form upon signup/profile completion - I can tab from each field to the next. In Safari, tabbing skips the dropdown fields entirely.

Expected: tabbing would move you to the next field as it does in Chrome. For dropdowns, the element is selected on tab and opened with enter.

**Comment by arottersman** [comment]
This happens because, by default, Safari disables tab access to nonform elements. There's an issue in [`bootstrap-select`](https://github.com/silviomoreto/bootstrap-select/issues/478) for this that links to a suggestion [to just enable tab access on safari](https://stackoverflow.com/questions/1848390/safari-ignoring-tabindex/1914496#1914496)
![screen shot 2017-11-02 at 10 27 19 am](https://user-images.githubusercontent.com/7633670/32332206-3d0f8218-bfbb-11e7-8461-7e148c68a20d.png)

It's still possible to access these elements via <kbd>Option</kbd> + <kbd>Tab</kbd> without enabling it.

If we really need to allow it, we could implement programatic tabbing to override the safari setting, but that feels a little nasty. @ajrobbins any input on how/if we should handle this?

**Comment by ajrobbins** [comment]
Given that explanation, I think we should make no change. Thanks for investigating, @arottersman
