### ISSUE TITLE
Onboarding profile modal should not be scrollable when modal is fully onscreen

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2482]
Observed on my macbook air 13 in: 
![scroll](https://user-images.githubusercontent.com/12868342/32448027-c638eed0-c2db-11e7-8b1b-09d5d028cbf3.gif)

Expected: modal is fixed in the center of the screen (since there appears to be room for it), with no scrolling unless the screen size is so small that scrolling is necessary.

**Comment by ajrobbins** [comment]
Observed on Safari as well

**Comment by rajadain** [comment]
I think it should be scrollable, to allow for when the screen is too short. See discussion on it here: https://github.com/WikiWatershed/model-my-watershed/pull/2462#issuecomment-341427131

**Comment by jwalgran** [comment]
It does need to be scrollable when the modal does not fit onscreen, but there is still a situation where the modal is fully visible but still scrollable. It looks like this is caused by the 72px margin at the top and bottom of the dialog.

<img width="1107" alt="screen shot 2017-11-06 at 10 21 43 am" src="https://user-images.githubusercontent.com/17363/32454500-9f18bd16-c2dc-11e7-8202-c2e01f95d448.png">

I am not sure if there is a way to say "only make this scrollable if the div itself it too tall, not the margin." Any tips @jfrankl?

**Comment by jfrankl** [comment]
If you remove the bottom margin does it address this issue? Ideally, the modal wouldn't change positions, and it wouldn't scroll when it fits on the page.

If that doesn't work, let me know and I'll spin up my VM and take a closer look.

**Comment by jwalgran** [comment]
Of course. That does appear to do exactly what we want. Thanks.
