### ISSUE TITLE
Create single UserSerializer

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#254]
There are two `UserSerializer`s used in the app, neither of which seem to be in the right spot.  Probably should be moved to the `user` app.

https://github.com/WikiWatershed/model-my-watershed/search?utf8=%E2%9C%93&q=UserSerializer

**Comment by jamesmcclain** [comment]
I am going to wait until @kdeloach returns before proceeding on this one.

This issue is that one of the `UserSerializers` derives from `serializers.HyperlinkedModelSerializer` which requires the request as part of its context.  It is fine in its current file, but raises exceptions if moved to a different file.

I would like to clarify whether it is necessary to derive `UserSerializers` from `serializers.HyperlinkedModelSerializer` (because the other `UserSerializers` simply derives from `serializer.ModelSerializer`).  If it is necessary, I would like to consult on whether it is advisable to move `UserSerializers` to a different app (a different file).

**Comment by mmcfarland** [comment]
I think that we should use a single `ModelSerializer` in the `user` app.  I don't think the hyperlink serializer is necessary.

**Comment by jamesmcclain** [comment]
Okay, I will give that one a try.

**Comment by kdeloach** [comment]
Wish I could provide more insight to this issue but I don't recall working this. It looks like the solution you came up with works well.

**Comment by jamesmcclain** [comment]
Many thanks.
