### ISSUE TITLE
Create unit conversion table

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2588]
Hi @SRGDamia1 !

I've created [this google spreadsheet](https://docs.google.com/spreadsheets/d/1Hn_PmhFz1mpDg79ZsF_gP1lZzVNCRvWQ2THsDhG6KBs/edit?usp=sharing) of all of the units in use in MMW right now. Can you:
- Pull out the unique units to convert
- Recommend a corresponding converted unit in the other mode we'll be enabling users to switch to (presumably "U.S. Customary")
- detail the formula we should use to convert from the original to the new unit

Let me know if you need anything further from us to support this!

/cc @aufdenkampe

**Comment by aufdenkampe** [comment]
@mmcfarland, @chitchens & @rajadain,

I have completed the Unit conversion tables and calculations, in the first tab of the [MMW Variables for Unit Conversion](https://docs.google.com/spreadsheets/d/1Hn_PmhFz1mpDg79ZsF_gP1lZzVNCRvWQ2THsDhG6KBs/edit#gid=0) Google Doc.

Please refer to the last column "Value US Customary unit" (column U) to see the formula to convert from a value in our metric unit to our value in US Customary Units.

Column M shows the Units abbreviations from our source, but I'm just realizing that some of those are weird and will need to modified.

cc: @darscott, @SRGDamia1

**Comment by aufdenkampe** [comment]
I think I just cleaned up all the abbreviations. Let me know if any look like they need to be revisited.

**Comment by rajadain** [comment]
I just did another pass of the app and listed a few more spots:

![image](https://user-images.githubusercontent.com/1430060/47525518-758bda00-d86b-11e8-9351-1f148a7722a2.png)

Almost all of them have units that have already been accounted in the spreadsheet though. The only new one we need a conversion for is `kg/ha/yr`.

**Comment by aufdenkampe** [comment]
@rajadain, I updated the [MMW Variables for Unit Conversion](https://docs.google.com/spreadsheets/d/1Hn_PmhFz1mpDg79ZsF_gP1lZzVNCRvWQ2THsDhG6KBs/edit#gid=0) Google Sheet with conversions for all additional units.

Regarding the *new* unit `kg/ha/yr` and it's conversion to `lb/ac/yr`: I pointed this to existing units `kg/ha` and `lb/ac` because the combined conversion factors are identical, and also because every other instance in the model for Loads and Loading Rates all *imply* average annual values in units that technically should all be displayed as "per year". Unfortunately we've been rather inconsistent in our labeling and display, largely because of all the diverse sources that we've integrated here. Eventually, we'll clean up the way we display things.

Let me know if you need more info.

**Comment by aufdenkampe** [comment]
Barry just gave my table a thumbs up. It all looks good.

**Comment by rajadain** [comment]
Closing this as Unit Conversion has been implemented.
