### ISSUE TITLE
Create painted tiles for elevation (cm)

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2629]
As was done in https://github.com/WikiWatershed/model-my-watershed/issues/2348, create painted tiles with a stretched color ramp. The raw data (full tif) is in the azavea-datahub `datahub-rawdata-us-east-1` at NEDSnapshot/elevation_full.tif

Summary stats from ArcMap for that tif are:
![screen shot 2018-01-29 at 2 48 14 pm](https://user-images.githubusercontent.com/12868342/35530901-70e9bb16-0503-11e8-8d6e-e2535233e0d0.png)

Here are the color breaks (RGB) to use for the stretched color ramp:
* -8560 (min)-  0,92,230
* -2000 -  191,233,235
* 2000 -  186,230, 153
* 10,000 -  126,204,88
* 25,000 -  42,133,60
* 75,000 -  204,175,29
* 200,000 -  189,70,2
* 275,000 -  107,45,12
* 325,000 -  148,114, 95
* 400,000 -  194,194,194
* 441,266 (max)-  255,255,255

When the color breaks are implemented, take screenshots at full opacity for the following AoIs (remove .txt) and check them with Anthony before implementing in MMW.

[boulder-aoi.geojson.txt](https://github.com/WikiWatershed/model-my-watershed/files/1675005/boulder-aoi.geojson.txt)
[delaware-aoi.geojson.txt](https://github.com/WikiWatershed/model-my-watershed/files/1675006/delaware-aoi.geojson.txt)

**Comment by kellyi** [comment]
13 zoom levels

**Comment by arottersman** [comment]
Bad (but hardly surprising) news. I made a mistake and the NED ingest's spatial keys are messed up. Note the negative value in the metadata:

<img width="386" alt="screen shot 2018-02-13 at 9 22 01 am" src="https://user-images.githubusercontent.com/7633670/36154422-6617c56e-109f-11e8-8007-73d94a796060.png">

I believe I needed to [re-tile the raster after reprojecting it](http://geotrellis.readthedocs.io/en/latest/guide/rasters.html#on-layer-reprojection). The consequences are likely:

* We can't perform operations that touch the whole raster because at some point we'll try to read the badly keyed tiles and the operation will fail. This means we can't paint the whole raster or get its histograms
* The analyze service (terrain) with the layer may fail unexpectedly for some AOIs that rely on the badly keyed  tiles

So before painting the layer, I am going to:

* Modify our [`RetileLayer.scala`](https://github.com/azavea/civic-apps-etl/blob/master/mmw-ingest/src/main/scala/RetileLayer.scala) to fix the NED layer (we just need to tweak the class's assumption of a certain cell type)
* Modify the initial ingest class/etl readme so we don't do this again

------

Unrelated to the bad ingest, Arianna and I noticed we might need some additional explicit breaks in the color ramp, particularly between 75,000 and 200,000 where the implicit ones result in a rather underwhelming Boulder. While the ingest-fix is in progress we can still play with what works for the color ramps and move the Anthony-check step along.

<img width="422" alt="screen shot 2018-02-12 at 1 27 16 pm" src="https://user-images.githubusercontent.com/7633670/36155010-32a659be-10a1-11e8-9e14-da08faafab8e.png">

**Comment by arottersman** [comment]
```scala  
      -8560.0  -> RGB(0,92,230    ),
        -8000.0  -> RGB(38,120,188  ),
        -2000.0  -> RGB(161,207,219 ),
        0.0      -> RGB(206,245,221 ),
        2000.0   -> RGB(224,247,121 ),
        10000.0  -> RGB(126,204,88  ),
        25000.0  -> RGB(42,133,60   ),
        75000.0  -> RGB(204,175,29  ),
        140000.0 -> RGB(201,154,23  ),
        200000.0 -> RGB(189,70,2    ),
        275000.0 -> RGB(96,39,9     ),
        300000.0 -> RGB(107,45,12   ),
        325000.0 -> RGB(148,114, 95 ),
        350000.0 -> RGB(178,153,139 ),
        400000.0 -> RGB(194,194,194 ),
        441266.0 -> RGB(255,255,255 ))
```
