### ISSUE TITLE
Non-project owner opening project via HS should not be able to edit in MMW

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2670]
Scenario:
- MMW user creates project and exports to HS
- Another HS user (user 2) opens the resource in MMW (not the project owner)
- Project is successfully opened in MMW

Currently, user 2 is able to edit the project as if they were the project owner. Desired behavior: that project is locked for editing. If the user wants to edit, they need to make a copy of the project to their own account and edit that.

For this card, we should just lock the project to editing, as if they had opened another user's shared MMW project when they are not the owner.

**Comment by arottersman** [comment]
@jwalgran dug into this a bit for #2671: the underlying bug is any public project with only a Current Conditions scenario still has the "Add changes to this area" button. If you click this button a new scenario is created that you're able to edit. The edits are not persisted anywhere, so it's not so bad, but it is pretty misleading.
