### ISSUE TITLE
Sub-basin: Add Source Details Table for AoI

### ISSUE THREAD

**Issue by arottersman** [WikiWatershed/model-my-watershed#2724]
Display the attenuated results for the entire AOI under the "details" tab of the sub-basin view:
![screen shot 2018-03-19 at 5 03 18 pm](https://user-images.githubusercontent.com/7633670/37622205-765d0872-2b97-11e8-8aa6-ec7727aa9caa.png)

<img width="483" alt="screen shot 2018-03-13 at 3 56 55 pm" src="https://user-images.githubusercontent.com/7633670/37370200-d269b166-26e1-11e8-925f-c2fcf1c8ffac.png">

**Comment by aufdenkampe** [comment]
For the "Sources" tab (formerly "Details) when viewing AoI-level model results for Water Quality, please mimic the following table, which has different column headers and units than the one shown above (which has errors). The live mockup can be found in the [AoI or HUC12 Source Details Table](https://docs.google.com/spreadsheets/d/1OzuN-3SV3_CHrVDoHSRd7ukGMCvVrWpUnnMVik_ZpT8/edit#gid=0) Google Sheet.

<img width="812" alt="screen shot 2018-04-04 at 11 28 23 am" src="https://user-images.githubusercontent.com/5166036/38320849-55ddca8a-37fb-11e8-8142-4362e8d9f904.png">

**Comment by aufdenkampe** [comment]
Barry brings up the suggestion, in his [Model output schema for sub-basinmodeling.docx](https://drive.google.com/open?id=1KP0mhgM441_OHChgge0VPtyC1dT2_94j), to have footnotes (see his doc for a mockup) or perhaps tooltips for each of the Source types, to provide information about how Loading Rates are normalized. I like this suggestion. 

Here is his footnote key:

Hay/Pasture1
Cropland1
Wooded Areas1
Open Land1
Low-Density Developed1
Medium-Density Developed1
High-Density Developed1
Farm Animals2
Streambank Erosion 3
Subsurface Flow3
Point Sources3
Septic Systems4
 
1 Loading rate calculated as source load/source area
2 Loading rate calculated as source load / (Hay/Pasture area + Cropland area)
3 Loading rate calculated as source load / total area
4 Loading rate calculated as source load / low-density developed area
5 Loading rate calculated as total load / total area

**Comment by aufdenkampe** [comment]
Alice had some good questions based on our mockups:

- Do we still want to remove this Other Upland Areas row? 
- How should we calculate the loading rates for wetlands and barren areas (if we should calculate them at all)​?

The question came up because your mockup does not have these three source categories: Wetlands, Barren Areas or Other Upland Areas. However, I based my mockup on the Water quality source categories currently used in MMW. See https://github.com/WikiWatershed/model-my-watershed/issues/2724, my AoI or HUC12 Source Details Table Google Sheet and this MMW example: https://app.wikiwatershed.org/project/21847/scenario/35945.

I'm presuming we want to keep these categories, and calculate them as such:

- Wetlands, as = Source_Total_Load/Source_area
- Barren Areas, as = Source_Total_Load/Source_area
- Other Upland Areas​

​What is the Source_area for this?
Barry, let me know if this is correct, and how to address "Other Upland Areas"

Also, should we list the following Area values for these sources?
- ​Farm Animals, where Source_area = (Hay/Pasture area + Cropland area)
- Stream bank erosion, where Source_area =  Total_AOI_area
- Subsurface flow, where Source_area =  Total_AOI_area
- Point sources, where Source_area =  Total_AOI_area
- Septic systems, where Source_area =  low-density developed area
I thing this is a good idea. Listing these will demonstrate our assumptions. The sum of all the source areas will be larger than the Entire Area, but that's OK, because we list the Entire Area separately.

Barry, what do you think of that?
