### ISSUE TITLE
Guidance on submitting initial PR's for Monitor MW Water Quality Portal implementation

### ISSUE THREAD

**Issue by emiliom** [WikiWatershed/model-my-watershed#2801]
@mmcfarland and @rajadain : following up on our call a week ago about the initial (and very preliminary) implementation of a new Monitor MW catalog, for the Water Quality Portal.

Let @lsetiawan (Don) and I know how you'd like us to proceed in submitting a first PR. How small should it be? Would you prefer that we have this higher-level exchange over email or some other medium first, rather than github issues?

Should we first have a call this week to discuss this? 

Don has already rebased his clone with a recent master. I suspect he'll probably need to rebase again once we're ready to submit a PR, but it should be easier now. Also, we plan to make additional progress this week with this catalog implementation; there is still plenty of work to do, specially with respect to enabling fleshed out result "details".

**Comment by ajrobbins** [comment]
Hi @emiliom @lsetiawan ! For an exchange like this, I think email is best so the repository issues can ideally be tied to issues with the application. For the PRs, thanks for checking on the best way to move ahead with your contributions.

In general, smaller PR's would be preferable to larger ones. Each PR should have a clear purpose and documentation (with demo, testing instructions, etc to go along with it). This is described in general here: https://www.azavea.com/blog/2017/05/08/github-pull-request-template-workflow/

Early-stage "Work In Progress" PRs are encouraged, so even if it's not completely ready for review we can spot any potential red flags and alert you before you put too much work into something.

All PRs will have to be reviewed before merging, so please assign to @rajadain for review when ready.

Final note - we noticed that you mentioned rebasing on `master` - all PRs should be targeted to `develop`, so that's what you'll want to rebase on.

**Comment by emiliom** [comment]
Closing issue. Shifting the discussion to email.
