### ISSUE TITLE
Mismatch between Pt Source Analyze results and overlay

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2812]
Dave Arscott observed an obvious mismatch between the results returned in the Point Sources analyze tab and the "EPA Permitted Point Sources" overlay, in the White Clay Creek HUC 10 at the PA-Delaware border.

![screen shot 2018-04-30 at 5 09 44 pm](https://user-images.githubusercontent.com/12868342/39450566-cabf4e16-4c99-11e8-90bb-866f0a4d4c10.png)

Observed: three results in the analyze table, ~16 in the overlay.

Expected: the number of results, and their details, should match.

I have a suspicion that this may be related to the fact that there are two different data sets in use here: NPDES national point source data, which is available nationally, and DRB-specific data provided by Scott Haag that supposedly has more points. Per https://github.com/WikiWatershed/model-my-watershed/pull/1449, we are supposed to be using the DRB-specific data in Analyze when the AoI is within the DRB, so the results from Analysis + viz should match. This is the data that's used in the visualized overlay. (under observations tab in layer selector). Perhaps we are not actually using the DRB-specific data for analyze, and are in fact using the sparser national data?

White Clay Creek is a bit hard to find via the geocoder, so you can select it (HUC10) in the Kennett Square area or upload this geojson, attached.
[White Clay Creek, HUC-10 Watershed.geojson.txt](https://github.com/WikiWatershed/model-my-watershed/files/1962190/White.Clay.Creek.HUC-10.Watershed.geojson.txt)

**Comment by rajadain** [comment]
There are three shapes in this picture:

![image](https://user-images.githubusercontent.com/1430060/40320750-aee7579e-5cfa-11e8-9f2f-b39b21ba90ab.png)

Green is White Clay Creek HUC-10. Red is the DRB boundary. Blue is a simplified, buffered DRB boundary. When checking to see if a shape is within the DRB or not, currently we compare against the red. In my testing I found that many of these edge cases (literally) are not counted as being "within" the DRB.

I'm going to switch to comparing against the blue instead of the red.
