### ISSUE TITLE
Subbasin modeling timeout on HUC8

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2820]
Reported by Dave Arscott and replicated: timeout on Lower Susquehanna-Swatara, HUC-8 Subbasin. Size is 4,866 sq km.

**Comment by rajadain** [comment]
Took a brief look in local Celery, and the behavior there is very similar to #2811, where Celery receives tasks for running gwlfe chunks and chord unlock, but doesn't actually run GWLF-E. In contrast with #2811, here the same behavior is observed both in development and local.

Would recommend taking a similar approach as used there: add `print` statements in and around the `apps.modeling.tasks.run_subbasin_gwlfe_chunks` tasks and see what is the last statement to execute before silently crashing.

Optionally, see if the error / crash can be made more vocal, so it errors out instead of polling forever for the user, and also reports it to Rollbar.

**Comment by rajadain** [comment]
Shares points with #2826.

**Comment by rajadain** [comment]
Fixed by #2835.
