### ISSUE TITLE
Production release 1.24

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2880]
Deployment Checklist:

~- [ ] Clear PA Municipalities tile cache #2879~
~- [ ] Add "Edit in WikiWatershed" resource to HydroShare #3003~
~- [ ] Point to SRAT_DEV for initial deployment, change to SRAT_PROD after SRAT has been updated~

**Comment by hectcastro** [comment]
- [ ] Update domain in Panopta
- [ ] Update `runoff.app.wikiwatershed.org` -> `runoff.modelmywatershed.org`
- [ ] Wire up CloudFront distributions for `app.wikiwatershed.org` -> `modelmywatershed.org`

**Comment by rajadain** [comment]
Update domain in HydroShare list of OAuth allowed sites.

**Comment by rajadain** [comment]
Run `./scripts/aws/setupdb.sh -q -m` to get new water quality tables installed.

**Comment by hectcastro** [comment]
**Questions**

- What does disabling `autosync` for HydroShare do?
- Do the SQL files for the following truncate the table and reload data?
  - `# Mapshed`
  - `ms_weather.sql.gz`
  - `ms_weather_station_1523624744.sql.gz`
  - `ms_pointsource.sql.gz`
  - `ms_pointsource_drb.sql.gz`
  - `ms_county_animals.sql.gz`
  - `# Municipalities`
  - `dep_urban_areas.sql.gz`
  - `dep_municipalities.sql.gz`

**Execution Steps**

```
$ ./scripts/aws/setupdb.sh -q -m # load_mapshed
$ ./scripts/aws/setupdb.sh -q -p # PA municipalities
``

**Comment by rajadain** [comment]
> What does disabling `autosync` for HydroShare do?

Previously we would export results to HydroShare on each change to a project. This was a user-defined flag, which was defaulted to `true`. This led to a number of export requests, each of which took a while to complete, and were at risk of queueing up and clogging the system if a user were to make many changes in quick succession.

The migration turns it to `false` for every user, and removes the button from the UI to turn it back on. This work was done in https://github.com/WikiWatershed/model-my-watershed/commit/4bb58a2ee4411146c1854ac7417b1999a2973609. Now users have to click "export" manually. In lieu of this auto-export, we now add a message near the export button that lets users know if the project has changed since the last export.

**Comment by rajadain** [comment]
> What is the process for updating `SRAT_DEV` and `SRAT_PROD`?

This is a matter of changing the `MMW_SRAT_CATCHMENT_API_URL` environment variable to `https://rychrnjrs6.execute-api.us-east-1.amazonaws.com/dev/SratRunModel_DEV` instead of `https://rychrnjrs6.execute-api.us-east-1.amazonaws.com/prod/SratRunModel` for Production. The current version of SRAT Production matches MMW Production, and the current version of SRAT Dev matches MMW Staging. When we promote MMW Staging to Production, we should point to the SRAT Dev URL, until they complete deploying it to production (a matter of hours). At that time, we should switch to pointing to SRAT Production.

This URL was changed in https://github.com/WikiWatershed/model-my-watershed/commit/5486a4d72f60bfdc9fded3f87db77010fc308937.

**Comment by rajadain** [comment]
> Do the SQL files for the following truncate the table and reload data?

Yes. These tables are read-only, and have their data initialized by the [`setupdb`](https://github.com/WikiWatershed/model-my-watershed/blob/develop/scripts/aws/setupdb.sh) script.

**Comment by rajadain** [comment]
Open in WikiWatershed and Edit in WikiWatershed both have successfully been configured in HydroShare:

![2018-12-27 16 54 34](https://user-images.githubusercontent.com/1430060/50495643-6c98bf80-09f8-11e9-875d-34c58c6e9e91.gif)

![2018-12-27 16 55 04](https://user-images.githubusercontent.com/1430060/50495645-702c4680-09f8-11e9-9505-bd817ae03979.gif)
