### ISSUE TITLE
Enable user to download BMP spreadsheet tool at Multiyear modeling stage

### ISSUE THREAD

**Issue by ajrobbins** [WikiWatershed/model-my-watershed#2893]
@aufdenkampe and BME have developed a BMP spreadsheet tool for use my PA DEP and potentially other interested parties to use in conjunction with the multiyear model output. This spreadsheet will live on a dedicated repo at this permanent link: https://github.com/WikiWatershed/MMW-BMP-spreadsheet-tool/raw/master/MMW_BMP_Spreadsheet_Tool.xlsx​

For this task, implement the UI element recommended by @jfrankl to trigger a download of the spreadsheet from the Multiyear model UI. Test in the 4 major browsers.

**Comment by rajadain** [comment]
That links 404s for me. This one works: https://raw.githubusercontent.com/WikiWatershed/MMW-BMP-spreadsheet-tool/master/MMW_BMP_Spreadsheet_Tool.xlsx.

Since @aufdenkampe spoke about linking to the documentation as well, one solution to that can be to add instructions, links to documentation and the tool, and any other supporting info, to [the README](https://github.com/WikiWatershed/MMW-BMP-spreadsheet-tool/blob/master/README.md).

I know this card is just for linking to the spreadsheet itself, but in the future if we want to add a link to the documentation as well, and if there isn't much room for it, we can switch to just linking to the repo which would have everything. Since the repo is public, it is open to the world. Users will not need to have a GitHub account to access any of it.

**Comment by aufdenkampe** [comment]
@rajadain, thanks for figuring out a better perma-link!

I want to link directly to the Excel file, because many users will not know how to navigate GitHub, especially for downloading a binary file. I've been surprised by watching people new to GitHub, when they get confused by the file structure, with excerpts from latest commits. Many of them don't even figure out that they can scroll down to a ReadMe file.

That said, we will definitely put much better documentation in the readme file, and we will point to those locations from links within the Excel file.

**Comment by ajrobbins** [comment]
@jfrankl  has provided a design for this, as a callout at the bottom of the water quality tab of the mapshed modeling sidebar:

![image](https://user-images.githubusercontent.com/12868342/43470330-519a9cd8-94b6-11e8-94ae-6345b2246835.png)

The actual text for the callout should be: 

>Get our [spreadsheet tool](https://raw.githubusercontent.com/WikiWatershed/MMW-BMP-spreadsheet-tool/master/MMW_BMP_Spreadsheet_Tool.xlsx) for advanced simulation of urban BMPs. 

>Designed to help meet permit renewal obligations in Pennsylvania, this tool can also be useful in other geographic regions.

Awaiting final confirmation of text by @aufdenkampe

**Comment by aufdenkampe** [comment]
How about these minor modification to the call-out text:

>Get our [BMP spreadsheet tool](https://raw.githubusercontent.com/WikiWatershed/MMW-BMP-spreadsheet-tool/master/MMW_BMP_Spreadsheet_Tool.xlsx) for advanced simulation of urban BMPs. 
>Designed to help meet permit renewal obligations in Pennsylvania, this tool can also be useful in other geographic regions. For more information, read our [documentation](https://github.com/WikiWatershed/MMW-BMP-spreadsheet-tool).

**Comment by ajrobbins** [comment]
LGTM! Thanks, @aufdenkampe

**Comment by jfrankl** [comment]
@aufdenkampe, what do you think of replacing "For more information, read our documentation." with "More ..." or "Read more" or something like that, with a link to the documentation? That will reduce the number of lines, and I suspect it will be equally or more clear to the user (people are accustomed to clicking on "More ..." type links).

**Comment by jfrankl** [comment]
Normally it wouldn't make a big difference, but space is precious on that view in particular.

![image](https://user-images.githubusercontent.com/1809908/43549956-1f017f1c-95b0-11e8-95e2-a0e3a0acf8cd.png)

**Comment by rajadain** [comment]
More screenshots in #2898

**Comment by aufdenkampe** [comment]
@jfrankl, I like your suggestions to shorten. Feel free to pick one. Thanks for the screenshots!

Here's a suggestion to shorten even more:

>Get our [BMP spreadsheet tool](https://raw.githubusercontent.com/WikiWatershed/MMW-BMP-spreadsheet-tool/master/MMW_BMP_Spreadsheet_Tool.xlsx) for advanced simulation of urban BMPs. Designed to help meet permit renewal obligations in Pennsylvania, this tool is also useful for other regions. [More...](https://github.com/WikiWatershed/MMW-BMP-spreadsheet-tool).

**Comment by rajadain** [comment]
Thanks @aufdenkampe I'll go with that.
