### ISSUE TITLE
Manual Entry: Add help links

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#2998]
The help content does not exist yet, but we will add a link to the appropriate help header from these modals.

![screenshot 2018-10-16 at 3 18 12 pm](https://user-images.githubusercontent.com/1014341/47041451-cc503000-d156-11e8-9a33-c708fe876756.png)

![screenshot 2018-10-16 at 3 17 13 pm](https://user-images.githubusercontent.com/1014341/47041452-cc503000-d156-11e8-8594-becb2d9f8d2d.png)

**Comment by rajadain** [comment]
For the first case (the Settings modal), will each tab have a separate help link or will there be one for the entire modal?

**Comment by rajadain** [comment]
There is only one link, to be used for both modals: https://wikiwatershed.org/documentation/mmw-tech/#description-and-editing-of-key-model-input-data-and-parameters.

@jfrankl do you have a recommendation for where to put it? How about a question mark icon on the right side of the header, since that area is currently empty?
