### ISSUE TITLE
Support modelmywatershed.org

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#3039]
In the near future, possibly with the next release, the site will be available at https://modelymywatershed.org/. This will be in addition to https://app.wikiwatershed.org/. Make it so that old URLs are redirected to the new one, and the app supports loading from both.

**Comment by hectcastro** [comment]
I would like to propose a counter-offer on this: Only make app.wikiwatershed.org redirect to modelymywatershed.org, and don't support operating the application from both.

(Worth noting that we currently support loading the application from: app.wikiwatershed.org and portal.bigcz.org.)

**Comment by rajadain** [comment]
I think they would agree to that. Tagging @aufdenkampe to confirm.

We should keep supporting portal.bigcz.org though.

**Comment by aufdenkampe** [comment]
I had originally been thinking that we would do exactly what @hectcastro suggested, where app.wikiwatershed.org redirects to modelymywatershed.org, which then loads the app.

We do indeed still want to support loading the application from portal.bigcz.org .

@darscott and @HeatherBrooks, is that what you had in mind?

**Comment by HeatherBrooks** [comment]
@hectcastro Sorry for the delay. We'd like to do what you and @aufdenkampe suggested earlier: redirect app.wikiwatershed.org to modelmywatershed.org. (The idea is that users will see modelmywatershed.org in the address bar of their browser.) So I should add the NS records you sent to modelmywatershed.org, rather than creating the subdomain app.modelmywatershed.org, correct?

**Comment by hectcastro** [comment]
Thanks for clarifying that, @HeatherBrooks. I instinctively added the `app.` prefix because often we find that clients want a marketing website of some kind on the bare domain vs. an actual application.

As a more practical example, we find that people usually want to decouple the update cycles of marketing copy (relatively low cost; can happen more frequently) with the update cycle of the application (relatively high cost; has historically only happened every few months).

If you feel confident something like this isn't case, we can move to accommodate serving the application directly on `modelmywatershed.org` (I'll have to update the set of NS records cited above, as they'd only be relevant to `app.modelmywatershed.org`).

**Comment by HeatherBrooks** [comment]
@hectcastro Thanks for the explanation. We have decided to use the bare domain for the application; marketing, documentation, help, etc., for the app will be on wikiwatershed.org. This is in line with what we are doing with monitormywatershed.org (and eventually, we hope, managemywatershed.org). The "tools" in the WikiWatershed Toolkit will live at their respective domains and supporting material will live on wikiwatershed.org, where it is easy for us to update. Sorry we didn't clarify this earlier so that you have the extra step of updating the NS records.

**Comment by hectcastro** [comment]
That makes sense. The additional detail is much appreciated.

The updated set of `NS` records are:

```
ns-1599.awsdns-07.co.uk.
ns-627.awsdns-14.net.
ns-447.awsdns-55.com.
ns-1080.awsdns-07.org.
```

Also, if you have any DNS records configured presently for `modelmywatershed.org`, please pass them a long as well so that whatever is in place now doesn't break as things start resolving from the new hosted zone.

From what I can tell, there is at least [one record](https://dnsrecords.io/modelmywatershed.org) for `modelmywatershed.org` that points to WP Engine. In Route 53, we can't use `CNAME` records for the hosted zone apex. WP Engine may have an IP that can be used as an `A` record in place of the `CNAME`.

**Comment by HeatherBrooks** [comment]
The CNAME records are pointing to our WikiWatershed installation on WP Engine and they will be removed when I set up the NS records. I don't think anyone has mentioned that we also own modelmywatershed.com and modelmywatershed.net. Should I point them to your NS records too or should I use a URL redirect to modelmywatershed.org? No rush on responding as I won't be tackling this until tomorrow. Thanks!

**Comment by hectcastro** [comment]
If you can handle the .com and .net redirects to `modelmywatershed.org` easily from within your existing registrar, I think keeping them there makes a lot of sense.

**Comment by HeatherBrooks** [comment]
Thank you. I have added the NS records and they appear to have finished [propagating](https://www.whatsmydns.net/#NS/modelmywatershed.org). I also removed the domain from WP Engine. Are you able to reach modelmywatershed.org? I'm getting a "site can't be reached" message on or off our network and in new incognito windows.

**Comment by HeatherBrooks** [comment]
Okay, great. I've added the domain back in WP Engine; the IP is 104.199.126.168.

**Comment by hectcastro** [comment]
Please check again. The changes appears to have propagated for us.

**Comment by HeatherBrooks** [comment]
Yep, modelmywatershed.org is directing to wikiwatershed.org again. www.modelmywatershed.org is not, but WP Engine says that it's pending on their end.

**Comment by hectcastro** [comment]
👍 Please let us know if you find out that an additional DNS record needs to be added for that in the meantime too.

**Comment by HeatherBrooks** [comment]
@hectcastro Looks like I will need you to add a DNS record for www.modelmywatershed.org.

**Comment by hectcastro** [comment]
Is this primarly to redirect from `www.modelmywatershed.org` -> `modelmywatershed.org`? If so, I can implement a redirect on our end in the same way we plan to deal with the redirect for `app.wikiwatershed.org` -> `modelmywatershed.org` after the next release.

**Comment by HeatherBrooks** [comment]
Yes, it's a redirect. Not sure which one (www or non-www) you prefer to set as the primary domain, but the other one should redirect to it.

**Comment by hectcastro** [comment]
I set up a redirect for `www.modelmywatershed.org` -> `modelmywatershed.org`:

```bash
$ http "https://www.modelmywatershed.org"
HTTP/1.1 301 Moved Permanently
Age: 5368
Connection: keep-alive
Content-Length: 0
Date: Fri, 14 Dec 2018 15:40:05 GMT
Location: https://modelmywatershed.org/
Server: AmazonS3
Via: 1.1 d671204b8bf6c2b9056c338588204020.cloudfront.net (CloudFront)
X-Amz-Cf-Id: QmrKV4k15dWaaMODQ-bUmXCpJQEI0Cq9HM9_ZNWnAQadZfOE9ZasRA==
X-Cache: Hit from cloudfront
```

**Comment by hectcastro** [comment]
I think we're good with the domain name change now, @HeatherBrooks @aufdenkampe.
