### ISSUE TITLE
Add modelmywatershed.org equivalent domains to Google API configuration

### ISSUE THREAD

**Issue by hectcastro** [WikiWatershed/model-my-watershed#3052]
The following error message appears when Google Maps JavaScript API is used when the application's domain is *.modelmywatershed.org`:

```
Google Maps JavaScript API error: RefererNotAllowedMapError
https://developers.google.com/maps/documentation/javascript/error-messages#referer-not-allowed-map-error
Your site URL to be authorized: https://staging.modelmywatershed.org/draw/
```

**Comment by mmcfarland** [comment]
@HeatherBrooks I believe you maintain the Stroud Google Maps API account.  You previously updated this

In the Google account for which you've generated a Google Maps API key for use in MMW, you'll need to authorize the new `modelmywatershed.org` domains.  This will be listed under your Credentials page for the project, with a field labeled "Accept requests from these HTTP referrers (web sites)"

I believe the value *.modelmywatershed.org/* will work.

Let me know if you have any questions.

**Comment by HeatherBrooks** [comment]
I've added it in as a wildcard as we did for wikiwatershed.org. Let me know if you need changes.
![image](https://user-images.githubusercontent.com/9368629/50021332-b8824800-ffa6-11e8-9a3c-d83ed4f9c4a1.png)

**Comment by mmcfarland** [comment]
@HeatherBrooks That's resolved the warnings, thanks for the quick response.

**Comment by mmcfarland** [comment]
Hi @HeatherBrooks, this issue was resolved for `staging.modelmywatershed.org` but isn't capturing `modelmywatershed.org`. The instructions I gave were similar to the original instructions and based on the screenshot, are applied in the same way the `wikiwatershed.org` domain was - so I expected it to work for both.

Can you add an additional referrer for the main domain: `*modelmywatershed.org/*` (note the dropped . in the beginning.  I'm hoping that this syntax will support both top-level and sub-domains.

**Comment by HeatherBrooks** [comment]
@mmcfarland I've just added the referrer for *modelmywatershed.org/*

**Comment by mmcfarland** [comment]
Perfect - both domains load without map errors now, thanks!
