### ISSUE TITLE
Cannot Export to HydroShare

### ISSUE THREAD

**Issue by hectcastro** [WikiWatershed/model-my-watershed#3067]
This is an issue to ensure that we finalize an update to the HydroShare application that is currently failing. We are unable to update the text associated with Model My Watershed within HydroShare.

See: https://github.com/WikiWatershed/model-my-watershed/issues/2880#issuecomment-447580712 (The _Add "Edit in WikiWatershed" resource to HydroShare_ bullet)

**Comment by rajadain** [comment]
The export to HydroShare is failing because `MMW_HYDROSHARE_BASE_URL` is not set in the Worker VMs

```
ubuntu@ip-10-0-3-254:~$ cat /etc/mmw.d/env/MMW_HYDROSHARE_BASE_URL 
ubuntu@ip-10-0-3-254:~$ 
```

So it defaults to `beta`. Also, `MMW_HYDROSHARE_SECRET_KEY` is not set. It _is_ set correctly in the App VMs, which is why logging in works correctly.

These two environment variables need to be populated in Workers just as they are in App. We need them in the Worker now because of #2897 which makes the export a Celery process.

**Comment by rajadain** [comment]
It is unclear why this was correctly set in the Worker during local development, but is missing in this Production deploy.

**Comment by hectcastro** [comment]
Something like https://github.com/WikiWatershed/model-my-watershed/commit/fa923b1f974f723889f89dcc10663b05029935cb#diff-53cd5caef2254f95d2e0402833625c67 needs to be included in `worker.py` for those variables to be available to a Celery task in staging/production.
