### ISSUE TITLE
Version Celery tasks

### ISSUE THREAD

**Issue by hectcastro** [WikiWatershed/model-my-watershed#316]
In cases where we attempt a blue/green deployment, there will be two versions of the Celery code attempting to process jobs. We need a way to version job specifications so that new Celery worker code avoids attempting older jobs while multiple stacks are present.

**Comment by rajadain** [comment]
Since the `worker` VM also has access to the main git repo, we could include an abbreviated SHA as the version number from the `app` in job requests. Celery could then check git inside `worker` to see if that SHA is available on its end. If so, then Celery is running an equal or later codebase than `app`.

But that isn't explicit enough, since different versions of MMW will work with the same version of Celery and vice versa. So do we start some form of semantic versioning for the `worker`?

**Comment by hectcastro** [comment]
Would it be less complicated to use stack color as the separator?

For example, `Blue` stack machines can only send tasks to the `Blue` queue (or add an attribute to the task indicating its color). Only `Blue` workers can process `Blue` tasks.

When we go to deploy, we bring up a new `Green` stack that functions similarly. As we cut over, we wait for tasks for `Blue` to drain as new tasks begin flowing down the `Green` path.

Getting the color from within the code may require interaction with the EC2 API via Boto. You can get the instance ID via the metadata service, but I don't think it gives you any information on tags. From there, you can query the EC2 API with the instance ID for tag details.

This might be something that goes in the production settings file. Non-production can get some consistent default queue name or color attribute. Failures in the process are OK, because those instances will just never get associated with the load balancer (failed health checks).

See also:

- https://boto.readthedocs.org/en/2.0/ref/boto.html#boto.utils.get_instance_metadata
- http://boto.readthedocs.org/en/latest/ref/ec2.html#module-boto.ec2.instance
