### ISSUE TITLE
Add button to support login with Concord Consortium Learn Portal

### ISSUE THREAD

**Issue by dboyer** [WikiWatershed/model-my-watershed#3263]
Note: Work should be associated with NSF ITEST billing.

This button behaves similarly to the existing Login with ITSI button. Text should read "Login to Learn Portal." 

Email with specific technical options forwarded to @rajadain

**Comment by rajadain** [comment]
Outline:

1. Create an account on https://learn.concord.org, for testing SSO
2. Add a button in the login UI that says "Login with Learn Portal"
3. Add back-end to handle the request and perform the OAuth dance for logging in
    - Uses same OAuth credentials as ITSI
4. Cannot use `?next=/` parameter in the response anymore, since the OAuth response needs to be to the same URL
    - Consider saving it in the session
