### ISSUE TITLE
Initial save on login

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#356]
Logging in should initiate a save if the current project isNew and you're on the `/model` page.  The theory being you may have been logged out, created a project with scenarios and decided to save it.

**Comment by mmcfarland** [comment]
Also remove the `save` menu item from projects.  Remember to remove the view events and the public/private menu list length tests.

**Comment by rajadain** [comment]
We might consider keeping the Save button for non-logged in users, clicking which would open the Login modal.

**Comment by mmcfarland** [comment]
Great idea.

**Comment by rajadain** [comment]
Thinking about the use case when a user is logged in but is viewing a public project owned by someone else. Should the "Save" button be visible then? If so, does it make sense to give it a behavior that would "Fork" the public project into the user's account?

Hmm, thinking about it a little more I think that overloading the "Save" button with such multiple meanings is not a good idea. If we ever decided to support forks, that button should just say "Fork" or "Clone" instead of "Save".

For this use case I will stick with removing the "Save" button for all logged in users, and only showing it for anonymous users viewing unsaved projects.

**Comment by mmcfarland** [comment]
Yeah, we've bounced some ideas around about this, but to keep things simple, any implicit/explicit "save" mechanism should only be available to project owners.
