### ISSUE TITLE
Clicking sign-up on the model page loses project, but keeps AoI

### ISSUE THREAD

**Issue by caseypt** [WikiWatershed/model-my-watershed#375]
Not sure if this is the correct behavior. I think, ideally, you could be on `/model`, sign-up, activate, and then login without ever leaving `/model`. This way any work that was started is not loss. This may be tricky because the sign-up modal changes the URL to `/sign-up`.

To reproduce:

- Visit the app as an anonymous user.
- Navigate to the modeling page.
- Click login then sign up.

**Comment by rajadain** [comment]
Thanks for making this issue. It is indeed incorrect behavior, that was added as part of #268 with the assumption that it would change in the future:

> This code does make certain assumptions that will have to be altered in the future. Currently we navigate to `/` as soon as a sign-up modal is dismissed, but once we allow anonymous users to have projects and give them an option to save them by creating an account, that would have to be changed to return them to the same page they were at when they started the sign-up process.
> https://github.com/WikiWatershed/model-my-watershed/pull/268#issuecomment-109056122

To refactor this I would propose changing https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/user/views.js#L160 back to instantiating a new `SignUpModalView` instance, instead of redirecting to the route. The `/sign-up` route would still work independently for users landing there, but it would not be activated when accessed via the UI.

**Comment by caseypt** [comment]
Cool. That looks like the appropriate fix.

**Comment by mmcfarland** [comment]
Related:  https://github.com/WikiWatershed/model-my-watershed/issues/260

**Comment by rajadain** [comment]
Shares a point with #356
