### ISSUE TITLE
Determine caching solution for boundary layers

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#447]
Boundary layers are very static, non-editable layers.  We should come up with an aggressive caching solution for them.

**Comment by hectcastro** [comment]
A technique presented to us for Treescount consists of:

- Browser request hits CloudFront and if it has a tile it serves it, otherwise it passes it through to its origin.
- The CloudFront origin is set to an S3 website housing static tiles. If it has a tile it serves it, otherwise a redirect rule for 4XX passes the request to tiler ELBs
- Tiler ELBs render tiles to the user, but also write the rendered tile to S3 (the same bucket setup as an S3 website above).

This provides a centralized and highly available tile cache, with minimal maintenance requirements. The biggest problem becomes cache invalidation. We need to remove or avoid serving stale tiles from S3 when data used by the tiler to render tiles changes.

**Comment by mmcfarland** [comment]
I really like that approach.  I was hemming on pre-generating all the tiles for the inefficiency (so many tiles won't be used) and maintenance; I like the on the fly caching better.

An additional complication may be that there are utfgrids generated for the tiles, too.  They should be as static as the pngs, so presumably we just do the same for those requests.
