### ISSUE TITLE
Don't geolocate if landing on `/model`

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#460]
Automatic geolocaiton is useful for new users just entering the system, but harmful if users land on a project with an already defined AoI and are zoomed away from it.

For example, see here: `<staging_url>/model/40/scenario/46`

The map is recentered if the results window is closed and opened, but not if users switch between tabs.

**Comment by mmcfarland** [comment]
I suspect this is not actually the geolocation, but the issue brought up in #401 about fitting bounds.

**Comment by rajadain** [comment]
Actually I think the "bug" of #401 is what allows the user to find the right AoI in this case. If you go to that URL, you will see that the AoI is actually around Facebook headquarters in Menlo Park, but if you land on it the map is centered around Philadelphia (if you have allowed geolocation that is).

**Comment by mmcfarland** [comment]
Not sure I'm seeing that behavior.  Going to `/model/40/scenario/46` shows me an active tab and the AoI + modifications in Menlo Park, the browser is reporting that the page is tracking my location.  If you then zoom away and toggle the results window, you're brought back to centered on the AoI because of #401.  Are you seeing something different?

**Comment by mmcfarland** [comment]
@rajadain showed me and verified this behavior.

**Comment by caseypt** [comment]
Shares a point with #479
