### ISSUE TITLE
Setup prototype template for compare design

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#536]
@ctaylo37 needs a place to develop a prototype for the compare designs, but being able to use the existing css.  We just need a sandbox that has the sass that we need so he can construct the html.

**Comment by rajadain** [comment]
There already exists a [`compare.html`](https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/apps/home/templates/home/compare.html). Should I update that so it plays well with changes made to `base.html` and looks like the prototype? Seems like it would be a fine sandbox since none of us touch it, and by extending `base.html` it gets all our styling.

**Comment by mmcfarland** [comment]
Yeah, I think that's probably a good idea.
