### ISSUE TITLE
Report and Accept ITSI Saved State

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#563]
ITSI Portal will communicate with MMW via [post messages](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) that communicate a saved state in an Activity.  My understanding of the workflow is as follows:

1. Upon visiting an Activity page, a URL is requested as descripted in #560 via an iframe (or new tab, probably for the former).
2. When the iframe loads, a post message is received with any existing saved state. 
3. The iframe is then polled periodically to provide any updated saved state.
4. Repeat for every page load

Currently, the only anticipated state to save is the student's project URL which may/will be different from the one originally requested in point 1 above due to the redirections mentioned in #560 and #561.  If state is received with a URL, the page should redirect to it.  The two methods ITSI uses for loading and save state are `loadInteractive` and `saveInteractive` and can be demoed at:

http://concord-consortium.github.io/lara-interactive-api/
(click "Mock Interactive" on the Interactive Source container to manually manipulate the values).

**Comment by mmcfarland** [comment]
API Documentation

http://concord-consortium.github.io/lara-interactive-api/docs/

**Comment by mmcfarland** [comment]
It appears Concord has developed a library for handling postMessages, may be worth an evaluation:

https://github.com/concord-consortium/iframe-phone

**Comment by rajadain** [comment]
Since all the state of our app is contained within the URL, perhaps we don't need to use the `loadInteractive` and `saveInteractive` methods in LARA, and instead use only the [`setLearnerUrl`](http://concord-consortium.github.io/lara-interactive-api/docs/#setlearnerurl) method to update the URL to be loaded for the student once we have the final state.

**Comment by rajadain** [comment]
I think we may need to revise some our reliance on the mutability of embedded URLs. After creating an activity with the Staging URL appended with `/?itsi_embed=true`, assigning it to a student, logging in as the student and then starting the activity, the following things happened:

 1. I was automatically logged in as my student account
 2. Because of #561, the blank project was automatically saved to my account
 3. I was able to proceed and manipulate the application with minimal deterrence (the only difficulty was because of the narrow viewport of the iframe)

However, once I got to my project and made some changes:

![image](https://cloud.githubusercontent.com/assets/1430060/9018173/4d9af18a-37aa-11e5-9d58-54b95367da13.png)

Sent a `setLearnerUrl` message:

```javascript
var message = {
    type: 'setLearnerUrl',
    content: 'https://mmw.******.com/project/191/scenario/379?itsi_embed=true'
};
postMessage(message, '*');
```
and then reloaded the page, I got the starting view again:

![image](https://cloud.githubusercontent.com/assets/1430060/9018623/c6d3b920-37ae-11e5-8f68-68683b4233a0.png)

Furthermore, this remark by Scott:

> The simplified 'itsi authoring mode' does not let authors enter in their own URLs.

makes me think that we will have to rethink our strategy for #560 since Teachers will not have any place to embed the URL we generate for them.

Will continue poking around on Monday.
