### ISSUE TITLE
Investigate feasibility of using spark-jobserver

### ISSUE THREAD

**Issue by hectcastro** [WikiWatershed/model-my-watershed#6]
[`spark-jobserver`](https://github.com/spark-jobserver/spark-jobserver) provides a REST interface for submitting Apache Spark jobs, JARs, and contexts. I could see this being the interface for interacting with  GeoTrellis Spark from Celery workers.

Lots of questions still around how to spread the `spark-jobserver` across AZs, and how to remove or mitigate the Spark Context single point of failure.

---

### Resources

- https://www.youtube.com/watch?v=oznpiqBf4ZY

**Comment by jamesmcclain** [comment]
I have been able to do a little work toward getting the MMW Scala code working on `spark-jobserver`: https://gist.github.com/jamesmcclain/86a131db281c6c490dbc#file-mmw-diff .  Applying that diff to the current mmw tree will allow you to build a jar file which *might* be compatible with `spark-jobserver`.

```shell
patch -p1 < mmw.diff
cd src/geop
sbt 'project  sparkjob' compile assembly
```

It is just the word count example grafted into the existing tree and Build.scala.  (I just realized that this diff does not include the word count code, but it is largely identical to https://github.com/spark-jobserver/spark-jobserver/blob/master/job-server-tests/src/spark.jobserver/WordCountExample.scala with `package spark.jobserver` replaced by `package com.azavea.mmw` and the addition of `import spark.jobserver.{SparkJob, SparkJobValidation, SparkJobValid, SparkJobInvalid}`).

I say that it *might* be compatible with `spark-jobserver` because I was not able to run it.  A 59 megabyte jar file is produced, but the `spark-jobserver` accepts a maximum of 30 megabytes by default.  I created this patch https://gist.github.com/jamesmcclain/86a131db281c6c490dbc#file-docker-jobserver-diff against https://github.com/azavea/docker-spark-jobserver to try to get around that, but unfortunately it does not work: when I try to do a `make test` docker throws something called "Error 7" and stops.  Oddly, the same behavior occurs when I try to use a similar technique to go below 30 megabytes, so clearly there is something wrong with this method.  It is probably better to just create a patched branch and use the git command in the Docker file to pull form that.  It also might make sense to pursue  some of the idea for reducing jar file size given here: https://github.com/ooyala/spark-jobserver/issues/5 .

**Comment by hectcastro** [comment]
First of all, thanks for trying to make an example work with Spark Job Server (from now on known as SJS). I got your example to work with SJS using the steps below.

First, add the following snippet to `etc/spark-jobserver.conf` and rebuild the container image with `make build`:

```scala
spray.can.server {
  parsing.max-content-length = 60m
}
```

Right now, the `make test` target does a few things. Instead of using that directly, I pulled out its first command (launching a running container from an image):

```bash
$ docker run -ti -p 8090:8090 --name spark-jobserver azavea/spark-jobserver
```

(This can be summarized as: run a container in the foreground, map 8090 inside the container to 8090 outside of it, name it `spark-jobserver`, and use the `azavea/spark-jobserver` image.)

After compiling the subproject, I submitted it to SJS from the container host. `make test` compiles the word count job and submits it via `curl` from within the container. Since the JAR we want to upload lives outside of the container, we need to upload it from there:

```bash
$ cd src/geop
$ sbt 'project sparkjob' compile assembly
$ curl --silent \
       --data-binary @sparkjob/target/scala-2.10/mmw-sparkjob-assembly-0.0.1.jar \
'http://localhost:8090/jars/test'
OK
$ curl --silent \
       --data 'input.string = a b c a b see' \
'http://localhost:8090/jobs?sync=true&appName=test&classPath=com.azavea.mmw.WordCountExample'
{
  "status": "OK",
  "result": {
    "a": 2,
    "b": 2,
    "see": 1,
    "c": 1
  }
}
```

Please let me know if you can reproduce.

**Comment by jamesmcclain** [comment]
Wow this is great, thanks!  I will definitely give this a try this afternoon.

**Comment by mmcfarland** [comment]
SJS is deployed, working on improvements and implementation details in other cards
