### ISSUE TITLE
Project should not autosave before interaction

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/model-my-watershed#602]
Previously, the user would have to add a scenario or make attribute changes to any project/scenario model for the project to start auto saving.  It now appears to begin saving immediately upon arrival to `/project`.

This is not related to #561 which is an ITSI specific feature.

**Comment by rajadain** [comment]
I believe this has been happening ever since #364 / #417

**Comment by rajadain** [comment]
The project and scenarios are auto-saved because of [this line which fetches results for scenarios](https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/modeling/controllers.js#L79), and because getting results and saving to the database are now tightly coupled as of #567. Since some of the work for this PR may overlap with #561, we should wait until that is ready before working on this.

**Comment by ajrobbins** [comment]
This is the current desired behavior, though we may implement explicit saving in the future.
