### ISSUE TITLE
Expose model information, assumptions, conversions, etc in UI

### ISSUE THREAD

**Issue by caseycesari** [WikiWatershed/model-my-watershed#657]
There have been several technical changes to the model or model data that should be exposed to the to the user in some way. They include, but are not limited to:
- Custom changes made to TR-55 that deviate from the documented model.
- Soil type generalizations (#646)

**Comment by jamesmcclain** [comment]
Here are a few that I can think of right now:
   * Instead of operating on relatively-homogeneous, connected areas as suggested in the TR-55 document, instead we do it independently at every pixel and add the results together.
   * Use Pitt Small Storm Hydrology model instead of TR-55 on built-types when the precipitation is <= 2 inches.
   * In addition to #646 which you mentioned above, I don't think we have decided how we are going to handle missing NLCD and soil data (both of which seem to be a pretty healthy percentage of the data).

**Comment by caseypt** [comment]
Describe what "Pre-columbian" is and the difference between that and the unmodified current conditions model results.

**Comment by jamesmcclain** [comment]
> Describe what "Pre-columbian" is and the difference between that and the unmodified current 
> conditions model results.

As it stands right now, any land use types that are considered to be "non-natural" are transformed to deciduous forest.  The definition of "non-natural" is given here: https://github.com/WikiWatershed/tr-55/blob/develop/tr55/tables.py#L431-L432

**Comment by ajrobbins** [comment]
Stroud has developed fairly extensive technical documentation here which should address these modifications and details: https://wikiwatershed.org/documentation/mmw-tech/

We also have a series of tooltips throughout the app with details.
