### ISSUE TITLE
Cannot change precipitation slider while job is running

### ISSUE THREAD

**Issue by lliss** [WikiWatershed/model-my-watershed#672]
If you attempt to change the precipitation slider while the job is running, it will be reset while you are dragging it because the view re-renders.

**Comment by rajadain** [comment]
This also happens if you try to select a new modification to draw: the dropdown will close before you have a chance to select a modification because the view re-renders.

Ideally, only the model output view would re-render when the results are returned, but I believe because we update the Scenario model with the returned results, it causes a full page re-render. We might investigate if addition of results to scenario can be done silently.

**Comment by mmcfarland** [comment]
This might become more of an obvious issue of the jobs take a while to complete, we should maybe up our sleep time to a more realistic (seeming) time of ~ 5 seconds.
