### ISSUE TITLE
Veg Basin causes model run to fail

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#851]
Seen on Staging at 45d29850039aad05d613d5ed1c3f6199a6221707. To reproduce:

 1. Create a new project, head to an editable scenario.
 2. Add any land cover modifications. See the model update correctly.
 3. Add conservation practice modifications. See the model update correctly.
 4. Add Veg Basin modification. See the model run blank out.
 5. Delete Veg Basin modification. See the model update correctly.

Demo:

![mmw-veg-basin-fail](https://cloud.githubusercontent.com/assets/1430060/10079999/303cb948-62bb-11e5-9324-93011da0235e.gif)

This is the XHR response received:

```json
{
    "error": "BMP infiltration_trench incompatible with soil d",
    "finished": "2015-09-24T16:53:25.539Z",
    "job_uuid": "6c4721b1-3917-4187-a522-75d0b89d999b",
    "result": "",
    "started": "2015-09-24T16:53:20.527Z",
    "status": "failed"
}
```

**Comment by mmcfarland** [comment]
Note the error in the response, we don't have curve numbers for almost all conservation types and soil type D.  Since the soil type is being generated deterministically, it'll fail consistently now until we get those curve numbers.  

I think we can close this in favor this issue which is tracking getting D type CN values.
https://github.com/WikiWatershed/tr-55/issues/34

**Comment by rajadain** [comment]
Closed in favor of https://github.com/WikiWatershed/tr-55/issues/34
