### ISSUE TITLE
Land Cover & Conservation Practice panes are 2 columns in Safari

### ISSUE THREAD

**Issue by arobbi7** [WikiWatershed/model-my-watershed#852]
![screen shot 2015-09-24 at 11 41 46 am](https://cloud.githubusercontent.com/assets/12868342/10080307/fbae7480-62bc-11e5-857b-a40b903962e6.png)

**Comment by rajadain** [comment]
Was Firefox maximized when you saw this? When running at full width on my Mac it looks okay (except for the overlapping text labels):

![image](https://cloud.githubusercontent.com/assets/1430060/10080459/b74ed220-62bd-11e5-95ad-8ad352a575b6.png)

**Comment by arobbi7** [comment]
@rajadain my bad, meant to write Safari

**Comment by rajadain** [comment]
@arobbi7 Can you check if this is still happening? I just checked on a pretty small Safari window and it looks okay:

![image](https://cloud.githubusercontent.com/assets/1430060/10433429/ca20e660-70df-11e5-9e5d-f8edeca59b12.png)

But I'm unsure if that's because I've upgraded to Safari 9, or because of something that's changed on MMW.

**Comment by arobbi7** [comment]
@rajadain I'm not seeing the 2 columns anymore. I'm also running Safari 9 (and I think I was originally, as well) so I guess something changed on MMW?

**Comment by rajadain** [comment]
Safari 9 was release on Sep 30 2015, which was 12 days ago [[wikipedia]](https://en.wikipedia.org/wiki/Safari_version_history). This issue was created 18 days ago, so it is quite likely that Safari 9 has fixed this. I unfortunately do not possess any machines with Safari 8 anymore, so cannot test and verify. However, Apple is pretty aggressive at deploying updates, and will update most machines automatically, so perhaps we don't have to worry about this anymore?

**Comment by mmcfarland** [comment]
Yeah, and since it was a mild display bug at that, I think the browser update is sufficient.

**Comment by rajadain** [comment]
Closing this in light of the above.
