### ISSUE TITLE
Follow up on #817

### ISSUE THREAD

**Issue by kdeloach** [WikiWatershed/model-my-watershed#854]
Follow up on #817 by fixing screenshot in Firefox.

**Comment by SRGDamia1** [comment]
I sent an email to @chitchens and @mmcfarland about it; but in short I'm having problem 1 from #817 happen every single time in every browser I've tried.  A teacher trying the system with students pointed it out as well.

**Comment by rajadain** [comment]
There seems to be an issue in ITSI where, instead of sending the entire contents of the iframe only sends the container element:

![image](https://cloud.githubusercontent.com/assets/1430060/10440995/119221c6-7112-11e5-8db0-5c71328fd436.png)

Curiously, if we use the same URL in the [LARA Interactive Playground](http://concord-consortium.github.io/lara-interactive-api/) it works correctly:

![image](https://cloud.githubusercontent.com/assets/1430060/10441014/42c7c23c-7112-11e5-89c4-28605b919c85.png)

It is most probably an ITSI configuration error. Perhaps @scytacki can offer some guidance.

It should be noted that we have had successful screenshots from within ITSI using Chrome in the past.

**Comment by scytacki** [comment]
It worked for me in Chrome and Firefox in ITSI on a OS X.  If MMW in the iframe doesn't respond to the request for the html of the iframe, then you will see the behavior above. This could also happen if MMW takes too long to respond.  When it works you should see in the console: `cant handle type: htmlFragResponse`. If you don't see that message then it means the iframe isn't sending back its html.

This might still be a bug in ITSI, but it is hard to tell when I can reproduce it.

**Comment by SRGDamia1** [comment]
The snapshot is showing nothing but the log-in page for me on Chrome, Firefox, and Internet Explorer on two different Windows computers.  MMW doesn't feel slow to me, but the snapshot takes forever.
![snapshot](https://cloud.githubusercontent.com/assets/5374350/10457594/2697afcc-7195-11e5-9aa7-dcb4fd42f0c7.jpg)

**Comment by rajadain** [comment]
Screenshots seem to be working now in Firefox on Windows (with the notable exception of offset maps):

![image](https://cloud.githubusercontent.com/assets/1430060/10458987/7afe750e-719b-11e5-93b3-0a467b61ce5f.png)

And accurately in Chrome on Windows:

![image](https://cloud.githubusercontent.com/assets/1430060/10459041/b6f851e2-719b-11e5-9f54-d21281cf4d97.png)

Unfortunately, [IE does not support `postMessage`](http://caniuse.com/#feat=x-doc-messaging) which is used to communicate with ITSI, and thus the experience there is broken in more ways than one.

While I have seen both the ITSI login and the MMW login screen in screenshots before, they have always been hard to reproduce (#817 point 1, https://github.com/WikiWatershed/model-my-watershed/issues/747#issuecomment-136890437).

Do you still see it on your end, @SRGDamia1?

**Comment by rajadain** [comment]
@scytacki When I said "ITSI configuration error", I meant the way we've setup our activity in ITSI, not a bug in ITSI itself. The evanescent nature of the bug makes it hard to pinpoint and investigate, but I suspect it is more on the MMW side than ITSI.

**Comment by rajadain** [comment]
It is worth noting that we only [enable screenshots](https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/core/itsiEmbed.js#L63-L64) when [we know we're in the embedded container](https://github.com/WikiWatershed/model-my-watershed/blob/develop/src/mmw/js/src/app.js#L22-L25). If there are login issues, it is possible that this flag does not get set correctly and Shutterbug never gets turned on, which would be consistent with @scytacki's diagnosis above.

**Comment by SRGDamia1** [comment]
I'm still having the same issues with both FF and Chrome.
![chrome snapshot](https://cloud.githubusercontent.com/assets/5374350/10460275/94e0ae5a-71a1-11e5-9d61-ccd969bf7324.jpg)
![ff screenshot](https://cloud.githubusercontent.com/assets/5374350/10460279/9674b45a-71a1-11e5-9882-c707e9611aec.jpg)

I have had log-in issues, though, and I always run MMW as a guest in the interactive.

**Comment by scytacki** [comment]
@rajadain can you elaborate on how you decide if you are in an ITSI container?
Currently the official ITSI Activities do not have the 'save state' option enabled for MMW. So if you are using the save state messages to determine this, that would explain why it seems to be consistent in the official activities.

**Comment by scytacki** [comment]
IE does support postMessage, you just can't send objects. The shutterbug.js code automatically converts all messages to strings when running in IE.
If you are using our [iframe-phone library](https://github.com/concord-consortium/iframe-phone) to do the other communication with ITSI, it will also [convert objects to strings](https://github.com/concord-consortium/iframe-phone/blob/master/lib/iframe-endpoint.js#L17-L21).  If you are not using iframe-phone you can copy the same code we have there to in order to handle IE.

**Comment by rajadain** [comment]
@scytacki Oh that's good to know. I will have to test more on IE to see why there were failures there. It is probably simplest for us to _always_ enable the screenshot capability, regardless of the user's login status or the app's embedded status, so that's the direction I'm moving in. Thanks so much for all the support!
