### ISSUE TITLE
ITSI Login and Screenshot Issues

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/model-my-watershed#950]
If a user wants to register with ITSI, but the autopopulated name is already present in MMW, the user gets a "Username already exists" prompt:

![image](https://cloud.githubusercontent.com/assets/1430060/10468136/68547ae0-71cb-11e5-9f4d-a043e200ae11.png)

If, discouraged by this and unaware that they can change their username, the user clicks "Continue as Guest", the draw tools don't render.

If the user can somehow get to a stage where the draw tools do render, the screenshot functionality does not work, and returns a login screen instead.

**Comment by SRGDamia1** [comment]
This is happening to me every time I try to log-in with ITSI.  I am redirected the ITSI page where I successfully log-in, but then I am taken back to this page where it seems that the application is trying to create a new user based on the information I just gave ITSI instead of logging in with it.

**Comment by mmcfarland** [comment]
@SRGDamia1 that actually is what's happening.  We create a user account in MMW (with no password) and link it to the ITSI user that was just authenticated.  If the ITSI user has no account in MMW yet, the dialog you see is the one to create that account based on the user info provided by ITSI.  We need to prompt because there could actually be an ITSI username (say mmcfarland) account already in MMW.  We're not going to default the MMW name to be `{{ITSI_USER}}.itsi` to make name collisions less likely.

We're doing some work now (https://github.com/WikiWatershed/model-my-watershed/pull/951) to make that whole process more explicit.

**Comment by SRGDamia1** [comment]
Question:  will there be a way to link an already existing ITSI account to an already existing MMW account?  This probably will not be a common workflow; I'm just curious.

**Comment by mmcfarland** [comment]
@SRGDamia1 We aren't planning a UI mechanism for that and there might some strange behavior when having both a setting to try to authenticate against oAuth ITSI and having a password in the system.  If it's something that comes up we'd have to investigate.

**Comment by mmcfarland** [comment]
@SRGDamia1 In the next release, there will be no "sign up" stage for users authenticating against ITSI for the fist time.  When they first visit MMW, if we find no MMW account for the ITSI user, we will simply create one automatically and use a unique name for their MMW account which they don't need to select.  This should make the workflow much more straightforward.  See the screenshots in #995 for a preview.

**Comment by SRGDamia1** [comment]
Looks awesome, thank you!
